services:
  step-ca:
    image: docker.io/smallstep/step-ca:0.30.2
    container_name: fiscalismia-pki
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000/tcp"
    volumes:
      - /usr/local/etc/step-ca:/home/step:z
    environment:
      - STEPPATH=/home/step
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      # the upstream Dockerfile runs setcap CAP_NET_BIND_SERVICE=+eip bin/step-ca
      # Even though we do not bind to privilidged ports < 1024, we have to grant this for compatibility
      - NET_BIND_SERVICE
      # - AUDIT_CONTROL
      # - AUDIT_READ
      # - AUDIT_WRITE
      # - BLOCK_SUSPEND
      # - BPF
      # - CHECKPOINT_RESTORE
      # - CHOWN
      # - DAC_OVERRIDE
      # - DAC_READ_SEARCH
      # - FOWNER
      # - FSETID
      # - IPC_LOCK
      # - IPC_OWNER
      # - KILL
      # - LEASE
      # - LINUX_IMMUTABLE
      # - MAC_ADMIN
      # - MAC_OVERRIDE
      # - MKNOD
      # - NET_ADMIN
      # - NET_BROADCAST
      # - NET_RAW
      # - PERFMON
      # - SETGID
      # - SETFCAP
      # - SETPCAP
      # - SETUID
      # - SYS_ADMIN
      # - SYS_BOOT
      # - SYS_CHROOT
      # - SYS_MODULE
      # - SYS_NICE
      # - SYS_PACCT
      # - SYS_PTRACE
      # - SYS_RAWIO
      # - SYS_RESOURCE
      # - SYS_TIME
      # - SYS_TTY_CONFIG
      # - SYSLOG
      # - WAKE_ALARM
    tmpfs:
      - /tmp:noexec,nosuid,size=64m
    healthcheck:
      test: ["CMD", "step", "ca", "health", "--ca-url", "https://127.0.0.1:9000", "--root", "/home/step/certs/root-ca.pem"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"
        reservations:
          memory: 64M
          cpus: "0.10"