variable "lambda_execution_role_name" {}
variable "lambda_execution_role_arn" {}
variable "apigw_route_throttler_name" {}
variable "sandbox_function_testing_name" {}
variable "notification_message_sender_name" {}
variable "terraform_destroy_trigger_name" {}
variable "apigw_route_throttler_description" {}
variable "sandbox_function_testing_description" {}
variable "notification_message_sender_description" {}
variable "terraform_destroy_trigger_description" {}
variable "layer_name" {}
variable "layer_description" {}
variable "infrastructure_runtime" {}
variable "infrastructure_s3_bucket" {}
variable "infrastructure_s3_prefix" {}
variable "region" {}
variable "handler_name" {}
variable "application_log_level" {}
variable "system_log_level" {}
variable "cloudwatch_log_retention_days" {
  type = number
}