variable "lambda_execution_role_name" {}
variable "lambda_execution_role_arn" {}
variable "apigw_route_throttler_name" {}
variable "sandbox_function_testing_name" {}
variable "notification_message_sender_name" {}
variable "terraform_destroy_trigger_name" {}
variable "apigw_route_throttler_description" {}
variable "sandbox_function_testing_description" {}
variable "notification_message_sender_description" {}
variable "terraform_destroy_trigger_description" {}
variable "layer_name" {}
variable "layer_description" {}
variable "infrastructure_runtime" {}
variable "infrastructure_s3_bucket" {}
variable "infrastructure_s3_prefix" {}
variable "region" {}
variable "handler_name" {}
variable "application_log_level" {}
variable "system_log_level" {}
variable "api_gateway_id" {}
variable "api_gateway_stage" {}
variable "post_img_route" {}
variable "post_raw_data_route" {}
variable "cloudwatch_log_retention_days" {}
variable "sns_topic_notification_message_sending_name" {}
variable "post_img_route_cloudwatch_alarm_name" {}
variable "raw_data_etl_route_cloudwatch_alarm_name" {}