name: TerraformModuleDestroyer Pipeline

on:
  # WEBHOOK INVOCATION VIA GITHUB API
  # See https://docs.github.com/en/rest/repos/repos?apiVersion=2026-03-10#create-a-repository-dispatch-event
  # See https://www.howtogeek.com/devops/how-to-trigger-github-actions-remotely-using-webhooks/
  # The fine-grained personal access token scoped to the org and repo, must have the following permission set: 
  # - Repository "Actions" repository permissions (read+write)
  # - Repository "Contents" repository permissions (read+write)
  repository_dispatch:
    types: [module_destroyer, test]

jobs:
  destroy-aws-infrastructure:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # for aws OIDC STS tokens to work
      contents: read
      actions: read

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v6.0.2
      # https://github.com/actions/checkout

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4.0.1
      # https://github.com/hashicorp/setup-terraform

    - name: Configure AWS Credentials with OIDC JWT Token for STS Access to Terraform Pipeline Role
      uses: aws-actions/configure-aws-credentials@v6.1.0
      # https://github.com/aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::010928217051:role/OpenID_Connect_GithubActions_TerraformPipeline
        role-session-name: TerraformModuleDestroyer_STSSession
        aws-region: ${{ vars.AWS_REGION }}

    - name: Handle test event
      if: github.event.action == 'test'
      run: |
        echo "Destroy AWS flag is: ${{ github.event.client_payload.destroy_aws }}"

    - name: Handle module_destroyer event
      if: github.event.action == 'module_destroyer'
      run: |
        echo "Destroy AWS flag is: ${{ github.event.client_payload.destroy_aws }}"

    - name: Destroy AWS resources
      if: ${{ github.event.action == 'module_destroyer' && github.event.client_payload.destroy_aws == true }}
      run: |
        echo "===== RECEIVED DESTRUCTION EVENT INVOCATION ====="
        echo "client_payload destroy_aws=${{ github.event.client_payload.destroy_aws }}"
        cd ${GITHUB_WORKSPACE}/terraform/aws/
        terraform init
        terraform plan -destroy \
          -var='budget_alarm_notification_email=${{ secrets.BUDGET_NOTIFICATION_EMAIL }}' \
          -target=module.route_53_dns \
          -target=module.api_gateway \
          -target=module.lambda_image_processing \
          -target=module.lambda_raw_data_etl \
          -target=module.infrastructure_lambdas \
          -target=module.cost_budget_alarms \
          -target=module.sns_topics \
          -target=module.cloudwatch_metric_alarms
