# See https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
# See https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_dispatch
# The fine-grained token must have the following permission set: "Actions" repository permissions (write)

name: TerraformModuleDestroyer Pipeline

on:
  workflow_dispatch:
    inputs:
      destroy_aws:
        description: 'Should AWS modules be destroyed?'
        required: true
        default: false
        type: boolean
      destroy_hcloud:
        description: 'Should Hetzner modules be destroyed?'
        required: true
        default: false
        type: boolean

jobs:
  destroy-aws-and-hcloud:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # for aws OIDC STS tokens to work
      contents: read
      actions: read

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v6.0.2
      # https://github.com/actions/checkout

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      # https://github.com/hashicorp/setup-terraform

    - name: Configure AWS Credentials with OIDC JWT Token for STS Access to Terraform Pipeline Role
      uses: aws-actions/configure-aws-credentials@v6.1.0
      # https://github.com/aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::010928217051:role/OpenID_Connect_GithubActions_TerraformPipeline
        role-session-name: TerraformModuleDestroyer_STSSession
        aws-region: ${{ vars.AWS_REGION }}

    - name: Query SSH public keys for Hcloud servers from AWS Secrets Manager
      env:
        SSH_KEY_SECRET_ID: fiscalismia-ssh-keys-hcloud
      run: |
        set -euo pipefail
        mkdir -p ~/.ssh/
        echo "Querying SSH public keys from AWS secret $SSH_KEY_SECRET_ID"
        # INFO: sed escapes and replaces literal newlines
        # since the ssh-keys are saved as is without json escapes
        SECRET_JSON=$(aws secretsmanager get-secret-value \
          --secret-id ${SSH_KEY_SECRET_ID} \
          --output text \
          --query SecretString \
          | sed ':a;N;$!ba;s/\n/\\n/g')

        KEY_NAMES=(
          "fiscalismia-infrastructure-master-key-hcloud.pub"
          "fiscalismia-demo-instance-key-hcloud.pub"
          "fiscalismia-production-instances-key-hcloud.pub"
          "fiscalismia-loadbalancer-instance-key-hcloud.pub"
          "fiscalismia-monitoring-instance-key-hcloud.pub"
          "fiscalismia-nat-gateway-instance-key-hcloud.pub"
        )

        for KEY_NAME in "${KEY_NAMES[@]}"; do
          echo "Extracting ${KEY_NAME}"
          echo "${SECRET_JSON}" | jq --raw-output --arg k "${KEY_NAME}" '.[$k]' \
            > ~/.ssh/${KEY_NAME}
        done

    - name: Destroy only AWS resources
      if: inputs.destroy_aws == true && inputs.destroy_hcloud == false
      run: |
        cd ${GITHUB_WORKSPACE}/terraform/aws/
        terraform init
        terraform plan -destroy \
          -var='budget_alarm_notification_email=${{ secrets.BUDGET_NOTIFICATION_EMAIL }}' \
          -target=module.route_53_dns \
          -target=module.api_gateway \
          -target=module.lambda_image_processing \
          -target=module.lambda_raw_data_etl \
          -target=module.infrastructure_lambdas \
          -target=module.cost_budget_alarms \
          -target=module.sns_topics \
          -target=module.cloudwatch_metric_alarms

    - name: Destroy only HCLOUD resources
      if: inputs.destroy_aws == false && inputs.destroy_hcloud == true
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: |
        cd ${GITHUB_WORKSPACE}/terraform/hetzner-cloud/
        terraform init
        terraform plan -destroy

    - name: Destroy AWS and Hetzner Cloud resources
      if: inputs.destroy_aws == true && inputs.destroy_hcloud == true
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: |
        cd ${GITHUB_WORKSPACE}/terraform/aws/
        terraform init
        terraform plan -destroy \
          -var='budget_alarm_notification_email=${{ secrets.BUDGET_NOTIFICATION_EMAIL }}' \
          -target=module.route_53_dns \
          -target=module.api_gateway \
          -target=module.lambda_image_processing \
          -target=module.lambda_raw_data_etl \
          -target=module.infrastructure_lambdas \
          -target=module.cost_budget_alarms \
          -target=module.sns_topics \
          -target=module.cloudwatch_metric_alarms

        cd ${GITHUB_WORKSPACE}/terraform/hetzner-cloud/
        terraform init
        terraform plan -destroy