name: Telegram-Bot-Testing

on:
  workflow_dispatch:
    inputs:
      send_ascii_bears:
        description: 'Send ASCII Bear Friends (HTML)'
        required: true
        default: true
        type: boolean
      send_base64jpg:
        description: 'Send JPEG Image'
        required: true
        default: true
        type: boolean
      test_trivial:
        description: 'Send Trivial Message'
        required: true
        default: false
        type: boolean
      test_markdownv2:
        description: 'Send MarkdownV2 Message'
        required: true
        default: false
        type: boolean
      test_html:
        description: 'Send Trivial Message'
        required: true
        default: false
        type: boolean
jobs:
  test-telegram:
    # Bot API Documentation https://core.telegram.org/bots/api#sendmessage
    runs-on: ubuntu-latest

    steps:

    # INFO: To find out your own chat id, send a message to the bot and listen at https://api.telegram.org/bot<TELEGRAM_API_TOKEN>/getUpdates
    - name: Trivial Bot Message
      if: inputs.test_trivial == true
      env:
        TELEGRAM_BOT_ENDPOINT: https://api.telegram.org/bot_TOKEN_PLACEHOLDER_/_METHOD_PLACEHOLDER_
        TELEGRAM_API_TOKEN: ${{ secrets.FISCALISMIA_MSG_TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
        SEND_MSG_METHOD: sendMessage
      run: |
        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
          | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
          | sed "s/_METHOD_PLACEHOLDER_/$SEND_MSG_METHOD/g" \
        )
        curl -sS "$ENDPOINT" \
          --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
          --data-urlencode "text=PRAISE THE SUN (from Github Actions)"

    - name: Markdown Encoded Bot Message
      if: inputs.test_markdownv2 == true
      env:
        TELEGRAM_BOT_ENDPOINT: https://api.telegram.org/bot_TOKEN_PLACEHOLDER_/_METHOD_PLACEHOLDER_
        TELEGRAM_API_TOKEN: ${{ secrets.FISCALISMIA_MSG_TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
        SEND_MSG_METHOD: sendMessage
      run: |
        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
          | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
          | sed "s/_METHOD_PLACEHOLDER_/$SEND_MSG_METHOD/g" \
        )

        msg_file="$(mktemp)"
        cat > "$msg_file" <<'MSG_EOF'
        \# GITHUB ACTIONS MULTILINE MARKDOWNV2
        *bold \*text*
        _italic \*text_
        __underline__
        ~strikethrough~
        ||spoiler||
        *bold _italic bold ~italic bold strikethrough ||italic bold strikethrough spoiler||~ __underline italic bold___ bold*
        [inline URL](http://www.example.com/)
        [inline mention of a user](tg://user?id=123456789)
        ![](tg://emoji?id=5368324170671202286)
        ![22:45 tomorrow](tg://time?unix=1647531900&format=wDT)
        ![22:45 tomorrow](tg://time?unix=1647531900&format=t)
        ![22:45 tomorrow](tg://time?unix=1647531900&format=r)
        ![22:45 tomorrow](tg://time?unix=1647531900)
        `inline fixed-width code`
        ```
        pre-formatted fixed-width code block
        ```
        ```python
        pre-formatted fixed-width code block written in the Python programming language
        ```
        >Block quotation started
        >Block quotation continued
        >Block quotation continued
        >Block quotation continued
        >The last line of the block quotation
        **>The expandable block quotation started right after the previous block quotation
        >It is separated from the previous block quotation by an empty bold entity
        >Expandable block quotation continued
        >Hidden by default part of the expandable block quotation started
        >Expandable block quotation continued
        >The last line of the expandable block quotation with the expandability mark||
        MSG_EOF

        cat $msg_file

        jq -n \
          --arg     chat_id "$TELEGRAM_CHAT_ID" \
          --rawfile text    "$msg_file" \
          '{chat_id: $chat_id, parse_mode: "MarkdownV2", text: $text}' \
        | curl -sS \
          -H 'Content-Type: application/json' \
          --data-binary @- \
          "$ENDPOINT"

    - name: HTML Encoded Bot Message
      if: inputs.test_telegram == true
      env:
        TELEGRAM_BOT_ENDPOINT: https://api.telegram.org/bot_TOKEN_PLACEHOLDER_/_METHOD_PLACEHOLDER_
        TELEGRAM_API_TOKEN: ${{ secrets.FISCALISMIA_MSG_TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
        SEND_MSG_METHOD: sendMessage
      run: |
        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
            | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
            | sed "s/_METHOD_PLACEHOLDER_/$SEND_MSG_METHOD/g" \
        )

        html_file=$(mktemp)

        cat > "$html_file" << 'HTML_EOF'
        <pre>Github Actions HTML Formatted Message</pre>
        <b>bold</b>, <strong>bold</strong>
        <i>italic</i>, <em>italic</em>
        <u>underline</u>, <ins>underline</ins>
        <s>strikethrough</s>, <strike>strikethrough</strike>, <del>strikethrough</del>
        <span class="tg-spoiler">spoiler</span>, <tg-spoiler>spoiler</tg-spoiler>
        <b>bold <i>italic bold <s>italic bold strikethrough <span class="tg-spoiler">italic bold strikethrough spoiler</span></s> <u>underline italic bold</u></i> bold</b>
        <a href="http://www.example.com/">inline URL</a>
        <a href="tg://user?id=123456789">inline mention of a user</a>
        <tg-emoji emoji-id="5368324170671202286">👍</tg-emoji>
        <tg-time unix="1647531900" format="wDT">22:45 tomorrow</tg-time>
        <tg-time unix="1647531900" format="t">22:45 tomorrow</tg-time>
        <tg-time unix="1647531900" format="r">22:45 tomorrow</tg-time>
        <tg-time unix="1647531900">22:45 tomorrow</tg-time>
        <code>inline fixed-width code</code>
        <pre>pre-formatted fixed-width code block</pre>
        <pre><code class="language-python">pre-formatted fixed-width code block written in the Python programming language</code></pre>
        <blockquote>Block quotation started\nBlock quotation continued\nThe last line of the block quotation</blockquote>
        <blockquote expandable>Expandable block quotation started\nExpandable block quotation continued\nExpandable block quotation continued\nHidden by default part of the block quotation started\nExpandable block quotation continued\nThe last line of the block quotation</blockquote>
        HTML_EOF
        ls -hla $html_file
        cat $html_file

        jq -n \
          --arg     chat_id "$TELEGRAM_CHAT_ID" \
          --rawfile html    "$html_file" \
          '{chat_id: $chat_id, parse_mode: "HTML", text: $html}' \
        | curl -sS \
          -H 'Content-Type: application/json' \
          --data-binary @- \
          "$ENDPOINT"

    - name: ASCII Bear Encoded Bot Message
      if: inputs.send_ascii_bears == true
      env:
        TELEGRAM_BOT_ENDPOINT: https://api.telegram.org/bot_TOKEN_PLACEHOLDER_/_METHOD_PLACEHOLDER_
        TELEGRAM_API_TOKEN: ${{ secrets.FISCALISMIA_MSG_TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
        SEND_MSG_METHOD: sendMessage
      run: |
        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
            | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
            | sed "s/_METHOD_PLACEHOLDER_/$SEND_MSG_METHOD/g" \
        )

        bears_file=$(mktemp)

        cat > "$bears_file" << 'BEARS_EOF'
        <b>ʕ•ᴥ•ʔ BEEP BEAR FRIENDS ʕ•ᴥ•ʔ</b>

        <code>ʕ•ᴥ•ʔ</code> idle
        <code>ʕっ•ᴥ•ʔっ⭐</code> star catch
        <code>⊂ʕ•ᴥ•⊂ʔ</code> hug
        <code>ʕっ•ᴥ•ʔっ</code> hug too
        <code>ฅʕ•ᴥ•ʔฅ</code> rawr
        <code>ʕ •ᴥ•ʔゝ☆</code> salute
        <code>ʕ •`ᴥ•´ʔ</code> hangry
        <code>┏ʕ •ᴥ•ʔ┛</code> dancing
        <code>ʕっ•ᴥ•ʔっ💕</code> loving
        <code>ʕง•ᴥ•ʔง</code> fight stance
        <code>ʕっ•ᴥ•ʔ⊃━☆ﾟ.*</code> casting magic
        <code>ʕノ•ᴥ•ʔノ ︵ ┻━┻</code> table flip
        <code>┬─┬ノʕ•ᴥ•ノʔ</code> table restore
        <code>ʕ－ᴥ－ʔ zZ</code> sleeping
        <code>ʕ◔ᴥ◔ʔ</code> eye roll
        <code>ʕ￣ᴥ￣ʔ</code> smug
        <code>ʕ*ᴥ*ʔ</code> starstruck
        <code>ʕ✿ᴥ✿ʔ</code> flower power
        <code>ʕ♡ᴥ♡ʔ</code> in love
        <code>ʕﾉ•ᴥ•ʔﾉ♡</code> love hug
        <code>ʕ&gt;ᴥ&lt;ʔ</code> squee
        <code>ʕ •́؈•̀)</code> retarded
        <code>ʕ;ᴥ;ʔ</code> crying
        <code>ʕxᴥxʔ</code> knocked out
        <code>ʕ•ᴥ•ʔ🎉</code> party
        <code>ʕ／•ᴥ•＼ʔ</code> hands up

        <i>boop a bear to copy it to your clipboard</i>
        BEARS_EOF

        jq -n \
          --arg     chat_id "$TELEGRAM_CHAT_ID" \
          --rawfile html    "$bears_file" \
          '{chat_id: $chat_id, parse_mode: "HTML", text: $html}' \
        | curl -sS \
          -H 'Content-Type: application/json' \
          --data-binary @- \
          "$ENDPOINT"

    - name: Send Base64 Image
      if: inputs.send_base64jpg == true
      env:
        TELEGRAM_BOT_ENDPOINT: https://api.telegram.org/bot_TOKEN_PLACEHOLDER_/_METHOD_PLACEHOLDER_
        TELEGRAM_API_TOKEN: ${{ secrets.FISCALISMIA_MSG_TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
        SEND_PHOTO_METHOD: sendPhoto
        SEND_MSG_METHOD: sendMessage
      run: |
        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
          | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
          | sed "s/_METHOD_PLACEHOLDER_/$SEND_MSG_METHOD/g" \
        )
        curl -sS "$ENDPOINT" \
          --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
          --data-urlencode "text=\[-|-]/ PRAISE THE SUN \[T]/"

        ENDPOINT=$( echo $TELEGRAM_BOT_ENDPOINT \
          | sed "s/_TOKEN_PLACEHOLDER_/$TELEGRAM_API_TOKEN/g" \
          | sed "s/_METHOD_PLACEHOLDER_/$SEND_PHOTO_METHOD/g" \
        )

        base64img=$(mktemp)
        cat > "$base64img" << 'IMG_EOF'
        /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkI
        CQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQ
        EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAFKAM4DAREA
        AhEBAxEB/8QAHQAAAQQDAQEAAAAAAAAAAAAABQMEBgcBAggACf/EAEwQAAEDAwMBBgMFBQUFBgQH
        AAECAwQABREGEiExBxMiQVFhFHGBCCMykaEVQlKxwRYzYnLRgqLh8PEJFyQ0Q2M1kpPCJTZEU2Rz
        g//EABwBAAIDAQEBAQAAAAAAAAAAAAIDAAEEBQYHCP/EADIRAAICAQQBAwMDAwQDAQEAAAABAhED
        BBIhMUETIlEFMmEUcYEGQpEjM6GxwdHwB1L/2gAMAwEAAhEDEQA/AOZJsd2K8pKHFLQDwcEVhUrR
        qktrEm31j8X86CUQ4setOJUORSHaHxpi6VD1FKbYxIzkn3FVYR4ceZqrZKMgnqM1LZKQqlxWOtFu
        ZW1Ht6QeTk1LbJtRt3+Ohx8qqrCPLlqA5UTUpFWJmUVedSqKsbSA6ofiPIyAadCW0Vki5IHulxB8
        WRWuMlJcGKScexISloOAs5piixbkjZMh49F8fOmLH8i3k+BUJlFIXgkHpS5KF0NjKfZgvODwr4NK
        2qL4HKbapjiMgPHHecmhcmmEopjxVqllOW0KPvjNRTfkjxrwMnY8lgnvePpRqaYt46G5kqScE8e9
        GuRbdGRKwfCv6GiBdCrb61g48vanerSqxLw2+EbocV/Eav1UD6L8IUTtx1FA8kQlimFBeLu2Pv1r
        Un/3Gs/zFcjdJHc2xZhF1s7n/mG44UepDYHNMUpi3GA0l3GMhWGGYziD0KfKmQjv7E5JLHykICcw
        ronaaksEolw1EWbqcSpPgOD6il+n8jXkVcDdT8pBwWlKHqRimLFGXkU80orqxxHkBXDreKp4UumS
        OdvtULuuxsf3u3HqKD0mM9ZCDi9oy2oLHXKeauOG3TYMs1K0rGxlOeWKd+k/Jn/W/g8JCz1xV/o1
        8lfrvwbl47fQ/OotHXkj134CEpTUq1RX47YDrKS0sJ6qIJOfyNJUI482yfTOm29VoVmxr3R4a/8A
        IHccUv8AEMiuhDHCHRwJ5Zz7EiGvNA/KjsXbMhSEjIQPyqNl02afGvIGElIHlkZrNKpPo2QUox7E
        nJK3FblqC1fLFVVBXfk8A6vlLZFC5RXYWyTHTMm4sDCCQPZVC9jCUZo1enyx41tqJ+eauMYvplSc
        o9oZvTXXfxtkAf4abGCXkTKbkuhNLoP7po3QHY5Zcwf7s/RVA2MSY9ZTu4wkZ9c0Dkg1BsdNwEuD
        JlJH0NUskS3il4HCLzNZACX0OD0Jz/OsyxzNLzYxBcqO4suvW+OVHqSnGf1o16q6FuWJ8sbPqgLV
        vEQN+yFYFMTyi5LCzCUw1jG4g+5q3mnHtArDCXTElApV9yofQ02OSMlyKninF8Dhpic4NyHAB7qx
        UbxsiWVHlxJ4B3Of71BvxLwMWPK12aJtkx84CVK9iqjWXGB6WUyLRcW1HEZ7jzA4ot2PsHbl6NTG
        kt8FhQ9sc1fqw+QHgyfB7u5AOCwofSrWSL8gvDJeBREdxXVCvyq/UXyV6T+BZxxyPb3Fuqc2sKBS
        gKwAD1rn6trenE9R9C92GcJ20vH/AGCkLddQHEnAPkfKuhCW6KZ5vPj9HLKD8M1V3vm4AflRpMU2
        jCSvopWfpUK4M7ArqAap0ErF2ilsf3YP5UiWNSfZojmcFVCgfUOjQ+lKeFfI1Z2/BgyVebY/OosE
        fknry+DHxPOFNCrWBeGU9Q/KM9+2rgxxn50XopeSvXb4oyGEOchpHyzQNbfIyL3doVQwUDhlIoJU
        +2HFNdIVCinq1n5UNL5CtrwbB7/Av8qmz8lepXhgpLqAeDTrZmpC7coJ6D9KF2MW3yhUvsrGXI4+
        eMUG6a6D242JLdinwpax7kkVanPyT04eDRSGCCptCgryOcip6lvknpce01TMlsjw5Tj0BFFshLyB
        vyR4oUTeZpG0ukj3ORU9GPyX68vg3buj3VRB+XFLlhj4Djml5Hbd8ltjwyHED0CsiqUK6YTnfaM/
        ttDnDx59doo/TkB6sB1FnJUoFKSU/KgcWg1NMOR3Yjze0tkE+YqqZTmvDBl3YShh1lpasvJKeR14
        pWeLaTXg630fPjhN45dyIray440UuZJT5kVs0s/bRg+tYqyqfyKuN81tRxKNC0vHCc1HJIJQbMdy
        6OdhpbyR+Q/Rn8GuHE9QanqRfTK9KS8CqZKk4A8P0oHFSGKbiLl2GtHPCvrS9k49DXPHJciaCEnh
        kkeuDVyTa7KjJJ9G5fQfxsn8qBQfhhucX2jAdbSrKFKH+zRNNqmCpRT4NhLeSeDn5pqlCJbySXX/
        AEKpmrUnCk/kKF40Esr8nviHfJFT04/JHll8Cq5Sz0QFf/5D/SlWmNaaGr011HRk/QYo1Gxbk0NV
        XCQrhYJHoRRqKXgByb8mBLbP42Sfko1ZV/k98WgfgQpP+1Uol0aKkrVkJUoD0zVpIpt/IiVI8waO
        xdGUuJAxwfmKp/gtV5N0OhHKRQtN+Qk4rwKfGLVgLbSoe4qtrXkvdF9oJQHgpQyD9DQtSQS2svL7
        OFsXcddxzFYaU9lDaC42XACo88YPOAeaW3La7L2xtUfRLtWjaQtWgm0XTs/tcmU80lAS5b2ljIHP
        JT1/1qpZ04xhJUy4Y3uck+jma16M+y3qFS0a401brOtSwCppKo3GefGjw5GfP3rbg9NR5F55ZMj9
        zbOe+1XQ3YnF7SWNN6AlXRFnlOttiaZaH0thXVXI5xnoSPnWuChJ7TNJNckL7c+yiT2IdoL2hX9S
        Q73iK1MZlRklAU04Mp3JP4VeoyarLhcKUl2SM/ggPxLnQjI9qxyxxNEc0jILh5S2R9KU4JeRyk30
        jVaneuEH2zVKK+SnJ/BoHRnC2k/Sj2NLhgb1fuQs3OfbOG0+Gq9P5YXqO6S4HBuSwAsNNqP+JFBt
        8BuRoq+LzhyBFUP8mKasViXnafQmu6MOH/yCEf5Vmp6BP1D+DAnt54aIHzoXgkug1qI+ULJmIUOA
        fypbxTQxZcbMGTb0jaZj3+yn/U1SgRzR5o2x1WFSJCffj/WiqgeB4INlI/8AjDiT/ja/41LZKRqq
        2W1X93cmF/MYqck9oku0RcbhKin5OYNS5FVEbuW+KkZElH0OatORTURq5EbTyl7I+VGpMBpDVaEp
        P4v0piFvg0PsoVYNs8lSs9aqibmEoTy0Ec0EooZGTOuPsYWhpi8xNUTnRsXLWUgkJShLSRlS1HhI
        ysDNZ8svTjwNjc3ydc/aG15Zl2WJCfebQ++yp1DaH0rODjChjhQxzkGk5X6kk6GYlsTRxbrXVjjV
        teas8d0pCSCUJyN2euOvnWjHuoVkZzTr/Ucm0vp1AkuxrkopU2tGW1NkdFAjBzWrFJ70Il1bMztf
        3PWt/evepJbl0kiHGYL8g7lnCT1Ixny5PNa9VKU5KvgHFtje4wuTa1nJihJ/wmsT3D04M8mTEQfu
        lrT9M0tpsNSSN1SYwHiCF/MVaTI5RGEhcdxWW0lB9B0o4pipNPo0bZkuHDah/wDMBRe1di/c+hRL
        VybVw2o4+RqNQZac0bB6UThcZKseqRVbEumEsjfaMKU2vwrihCvUcVOV5LuL8Gvwi8b21pVjyB5o
        t6fDA2NcoVC3mRjenmlOMWMUpRQ3joYVyp/b86p2Emh18K0ofdymFn0UsCqpl2hEsnOz4NpR9UrJ
        /kalFWJKt0hRy2yR7Zq7RVPwargzGRuWwQPeommSmJZPRTZ+gq6KbE17PRQokAzTg9D+dEgTZIQP
        xpz/ALVQhsnugrPcOY9lVCDtpbIxsDgP+KhYxHbH2YuzS5Xux6dft0e/TnBaZs1xiBe/2elsPOhC
        FHIO/GNwH8SQTnGKw6l2tttft2adO1CW5pP8MZdqDk7QqpGitaXrWchYlRprF61Pc2Z6YjCCouR4
        /coBSV5QnKyAQM+XNeop9csOca5qv2Oc+0fUllu6VN2y5MPgggKQ4k4J9RRxtdmWfLKW15epkBi0
        xLRcyytKCp7u15O4nzHQjFN0u71G2BkrakP9PrfkNSJkgoLjzvKkthAVhIGdqQAPoK6LblyxPQW5
        B/En60DRExVtl1z8CQfkaWxiNlIca/vEr4qv2L4Md7GXwptZPrmpTKtHkBonwpI+aqp2WqHLZ2fw
        4/zUNB7h0yqOo8qIPsQauiWKPW9p7lDrn/0zUK4EvgXmgQlSk+4TipdE/kbqhDPieV9RV7vwVt/J
        F1S5Kk4TMJ9s4q6Ksblx/PLhPvmoVQs3LktnKH1j5A0L5CFRd56eshR+ZNVSLtiqbtMHiU3v9+tV
        tRe5iqbu2f76Pj6VNpe75F2rhAd4KQPmaumVaY4Su3EfhbNWrKdHgiKr8GB7VCqRuhmPnlaR9Klk
        SF2ZUBo7VOdPWqaYVo+pH2M4UWDZlTSkpcYsVuhJBGABhbpH13pNYc09khqjuVAn7RcpuVNlJlLj
        qScqSlpOAlPUZz1NZYPdKzVJbY0ccT/s+a07SdQ/sy12GFFcuLqUxlzdrReyTjYnG49D6dK6GLHJ
        vgwzZANX/ZesOjNQy7HqfXTrE63XJNunNphgtwlZT4lhSirYUqSoKGMg5HnW/FjipJTYl21aBWse
        ynUPZHf5Gk9QsAgLU9DlJOW5TCj4XEK6EEY/5NOyx9OVLoCPuAL0dI9D9KVYW00DaB+EKB+ZFBZN
        pnulrPicO35n+tTdRNrF0Mw0Y3E/XFC5MJRRuTbh02k1XIXAi5dosPltA+fd5FWotlOSQ2Xq94HC
        G2//AKYq/SK9QXa1vOCdnfYB8toqenRPUs3GpnnwUlK3PZKU/wClVtJuGz1xSVbvgngT/hq6fyU2
        vg0a0VqHr8FGV8wRSnkiNWNiitL3tn+8s0dX+VVD6kfkNQfwaJs85J+8sQA9Qqq3fDL212PWbSte
        EfspgH1Uuiv8lUKnTJV4lMxEfJyq3k2njaIUdOHnmR7BWf6Vad+CqSGLzdoBKUhJPsnFGrAdDd0w
        Ep5az6eKi5K4Gq31JOWYmQPciroETU8tzq0EH2G6pRBW3sCbcI0BJdU7IdQ0kBscknFR8K2RW3R9
        Vfs73+0t6Wu6bHcluuOTClBjoCi4zHjNJO3I2kYSRn3+VcjP75m6C2x5AnaZr7TGkbnd7xqSTEku
        2mBCvNvacKe6fYc3KURvwHFeHYPIEjzxUxxp0i5O1bOY9Wdscu8v3DVehnpshTctqbHuEh1MeLGd
        RtWlXeOKSM7mkkhOckn3rXHJ6bp9/wDIhrcUj2pdvWrO17X8y5Wi2qvd4uUZDM/4ONvQ6pBUEq34
        ClAJVtyQBjFaXltbp8CGq4QQfi/aPvWj2LVq2JDkW63Nt/Bsy0hyUwhvPDa0klOUnBB4ICcjgGmL
        XY5rZJgvG48kMVJkgFt+GtCx18WMVfBadmiFFXKkvj5KoWShdpnveEPgf51c1VoujZcBeMGW0Klk
        aY2diFAyZqAPb/rVlUIIREJ2uTG+f4quyqF0QLb1VKj/AKVNzL2oVFstqx4XWj8jVOTJtQk7aIqe
        UPY+RFTeTaMH4204Eo/U1e4pxJozfbcoAuahiAH/ANxJ/pWPa/g17l8jhFysb6SFXuDz6LTmp6cv
        gm9fIu3Dtr6S4xd46kjrtcBq0mvBTkmDbjLtMMEJltuqHknmmRiwHJAhV3StX3MJTg/yGicClIUj
        Nqmq+8iBI9Agk0DltDpMXXaIaUlT9vUkepOCaim2U4IGvm0RlYSw2k+WVA0xWwHSGz14t7TeEBCl
        +gHAolFsq0gW5c5T7gaZQytS1BKQOpJ4AoqS5YFnZET7OUnsw7IGL7b7E3e9ezTHekqyEohtLOVN
        tfJPhJ6lR9BXDxar9drPTclGCurdWbdno4rSuRXb+pPtULR8f3bWgLKy6tCblciYzLKCkIJG4blk
        hP7qDnFacubS4JbE9z/HIMY5svPX7kEmXPs10pfGL9rTXtm7WZsZKQwzIlSkxWADnZ3ZCdyc+Wce
        1Cp5cyqMXBEahDmTsnH/AHeaq+0kW7xdocfS2mlNoMdiHGQwC2DwGW0gAIx+8rOfekS1OPSNxi7k
        LnlWTjouPQPY5pHs+ios+mLYlDC1/eSMZeex1K1Hkn9PasGbWTyO2DaXRKJemWJqlQwFtKRncEkH
        HuD1yR5Utahx5styXRUnal2d6Itds+FVZ5ztydyovbgjYM9QAOc11NHqcs3y6QEoJK0cma2kf2Uv
        zdtJmNxn07mZDwSUOHPQEHy88813drVbvIlTGaLvIc4UlS/QgYx+VTYglJmqlXN1WW0uEfWrqKJy
        zRbl0SnYsnHoRUqJXIzWZG7JSc/I0XBXI6jvvrAbLZUflVNItNkhtdpvriQuLbtwP8agKVJx8sYl
        L4CqrRqYpwYENPzNBcQqkIqsOoVHK7bCV8s1e6JVMXi9k1wdc7spKPmM0HrIP0yRweyKJGaxPnON
        t5yohgfzzmgeeT6QSxJdhVmx9mVlQTInF5SevgUf06VV5JF1CJlu/wDZWy5sQwtR92iamzJ8lboE
        ks03SVyUEWuApWf/AOOQPzIpUk49jItPokSdPWV9ILtsYGOdykjigTCoC3XSGlZrijInhvHVKHsU
        2MmugGkwDI0HoZGSzGEpz/G4T/Wi3y8srbH4A1w0/Z4IPdWCCkD1b3k/maJS/JNn4BuieyrU3bN2
        pWvTOlYqWotuU3KmONxfu4yQrPeLA6qONqEnqck8Ck6nURwQe7tkhhlkkkvB2H2n3btE1RbHdO6T
        0zd3btbSlpxyD3gejyEDaoFIG1aT1GD0PSvM4o1k/wBTo60se2PHbKYjfZV+3F2kSmrTqrUQhWZ9
        wE/tuYFKQjzUllOVnA8jj5iun+o0WDmMfd+DJ6Wom6vgvfR3/ZtdhvZ5CTfNYyJ+p762kPJXIc7i
        G08OQoMI6gEdFKUPasmf6tmlHbHgZH6apxe3sMT7U3bpZY75plpKtqVEcBOOBj9K5qk5I87KUuvI
        +n3FmEy7DtTBKdu5TuwFRAHUelMxo0Ql4Q5tVqt8aKxMRMEt+S38R1G1pOeVKPr7eVSbd14JKkyM
        9s1jsNx0+JLVwDs4ZSUoT+7/ABceQKTWrSTcJfgcnaOAdaSPj3pFn1Xbu+sshw4dZT9/Dd5w4nPX
        3HmK9npMkZQ9OXRjyJp7kSSydmOmZ1rjzrVeCWFIAQr5fWkZZSxycWa8cYzjaHT3Z0pv/wApeGnR
        /CtWKX6n4GbEap0GnpJZYX7h1P8ArU9Rk2Iwvs4hO/gQ2nPluz/I1azUU8ZtG7OEx3N4eQj/ACE5
        /WreZMnp0EkaNdQnLc8k+izx/Oq9RMvYeRoy8vZ7qbEAHr/1qnkiTa2IPaN1Awohclog+aBiq9SJ
        e1orWdq24S3SWpDyUKPH3pFaVjSEObYtHh6mmIC2nXClXIzKTz+tU5QRaUmE4Wl7gcOXFMpY6lDe
        F/ruoHkXgtQfkK22+wrC4Uq7O3JJSeHXMkH3/CaFwcv7glLb/aS+09rinVpijRspvHADRAH+8BSn
        grmxiy34FLlr9DqipceXFT1Uh1DeB9d1WsZHMBO6mYvkj4eHdERyTt3JZ4z80g0W1xXQNqXA1l2e
        5xnShV/BHUkKUarfx0Mjj57Bj1uipVukX57cf/bXilvI/g2Q09o7W+y/ptzQvZzaLBZHm29T9oVx
        XMl3BIw6xb0eFAyeU+FKj7c+teY1uqln1GyL81+yXf8Ak9p9O+j4dJpsmu1SuOOKdfM5/an+Emmy
        7ta9u+n9DR/7FdmttbnTmx3KHUeNtLh69OXF55Pv1NZc+sjjfpYlb/8Aux/0v+ltT9Txv6n9Rn6e
        Hy5cN14iv+F4+AjpiXcNNNv6m1ZfnLlfZzKEulQCUR0gZ7pCRwME8nzpe6T4s4+ojgzNLFj2QXSu
        2/y38/4SAPaF2tQk2N5yRJQlBSdxKsYo8eKUpCntxogMaTbdQwXLpMQVMFoFCg9tyeoIx9Pbis/q
        yg9p87yZLm/CtjK/XeOWY0G0W071KIKi6pasqwOucYp+Kbb4CjPxEELuK7FNEOetpLb7eNoPKgFH
        OPyrRJp0x98qyt9eds+ntC2x9u5yAJjUUFKVnKnlKKjtTnzUEqGK2aXTzzySguBsZUuEc2aglwtS
        PJFrmNq+MbEplAWN+M5HHsRXo9Kpwd10BJbuDFrF8YY7olMUJWQpIJSnd5nA9aflUbvwOxN0GWm5
        K0b3rqhA9SpVI/gaEYnd8A3FlfsonH6iq5LJBAtyJKB3MWOs/wAQzQttBJWKv6Wvb6T8EhKPbmqW
        ReS9rBj+j9aIBIZCsemf9aJZIA7JDIWnWUVWVxnPkUKIq3KDJtZlbuoQdpZwR1zuqrRKkSDT3YNp
        SArv5M5M0+WOB/WqnqJy6LjhiiZRez3ScdAR8BGIHQd0kfyFJ3y8sYox+B0nSOmmP7q3sA+oFTeS
        kYXpuxryfhEkDyB4qt5dA2ZY9NMZ7yyhZ8uTRKUmVSA0jTulJa9r2l1lJ8weKNSkvILin4ElaI00
        yAbfY1MK8lJcG79eanqvyyKC8Dcafvwd2wkuJQP41D/7RS5zibMMOQjZ9Baj1FqG12V51rbPmMxy
        CFdFKAPX2rma3WQ0ennqJ9RTf+DtYMKm0v8A78nbOqOwOxab0G/ctNXua1frXBceU+l8hLzYSe8Q
        Ej8KSncBj9a+D6D+tNZl+oVkVQk9v5V9c/8AZ6/Qf1I9frsek1uKLwSnH21VPqLtdtcXfDIb2OaN
        jWux/wDeFdHkqkyUrRbm9w+7R0Usj1POPQfOvqOmw+nG32zd/Wn12X1HVPRYuMWJ113JcN/sukNt
        V6pkILqC+VBWfOuljhZ4Sc6OTu2fX07uJUMzXNjW4bQryrt6TArTOTqszpqyc6G1jbrX2b2m7P3p
        LkVFvDhcdVtSEoSd6jnyGD+VcHVYpZNVKCjzZ4/KnLI/3H+le3LRbjPfNariPLVC/aO/JRhhSyhK
        8EDw7h/I9DRz0ebDLiPmv5GQg4MiLvaaNRXH4WVMUzHjwHpm5pJccbaWvwK9MlIBxW1aZxSv5r/2
        aoR6v5OetYagsmq50+9X+/ybiyGVREQX0jvm3kNnY4gAg4SNuFEeZ6mvRaaDxJRSNMkq5ZX2mr1J
        i32GkONlERwqYCRyklQVknzO4JOOnBrpwSd/lGZumXtbO0zWjSyhdkTcwo9UR0gn8gc1glhi/NGp
        ZJfBMrZqe9XDaJmmH4IVzkstqA+mc/pWeUEunY1Sb7QTuV+gWaL8VcUSNnqiED/KqjFydItyrsh1
        w7WnmHALLHmFonlZgjgevOadHBfYt5vgB6l7TbtOaDce5XVtJGD3TSGgr64yKZDCl3QEsrZH4Ou9
        UQFJLN3vxSk5KVPb0kfUU14ovwgFkkvLLG0P2uWiSlxrU0u4ofT+ErTvSR64SnIrNk07X2joZU/u
        Jqzrns6mE/8A4y1uHJC2lpP6il+lNeBnqR+TmmDG7SnBm3vXcg+bb6v9a6DeHyYUsoRMDteZSFuS
        L6kHph9f+tVeH4QVZfkIR9SdpluaDLhmkgdVI3KP1JzS3jxNh7siPDtE7TITm91x9QH7rgIH6Vfo
        4mV6mRCn/fdr5B2fDxDj+NtSv/uq/wBPjK9aY4HbJ2huIG+LaSk+ZY6f71V6GMv1Zg+TrXUd7cCb
        m/CYRnkstqSf0NV6UY9BxnJvkm2lL6WgGpGrZKWcYKW2+f1rJlj8I62mdnRH2YrbAvPbHpx1M1El
        qO65Iy4CFlSWlFPXjqB0r5//APoGolpvoOZx7dL/ACzv4J7ceR1ztf8Ay0v+mdidr2prRp7s11Fq
        G5fDoWiG9DjYUcqUsbUo+eeoHTmvz/8ARMOXU/UcODHbtpv+OW/2H/QtLk1P1LBix/8A9Jv+HbPn
        lO1ZfIcVMi3z7kylnxpLKnNjfvjoAfyr9D6fHqY0knSPrf1h/wBMajdLM4bpt20+b88rohl77SNZ
        XB4Op1BOfdQPCG07h9UpHP1rr4fVk+I8Hidb9L+g6PE1PLzLp7ra/ZL/AMopzXeq9SzXHhcGwtMg
        7CpSNhyfMCvQ6WHttqj5n9UWnxZNunm5/mqX8AzV991axphjSLM9122IZDR7tQ8KAR4eOn4cn1z8
        6PHp8XqvLXJw5Y1dorSLfLzYpTsmBMdaXIhrt7u47ssKABRz0GMD2rZLFDIkpLp3/JRMbBrrVEm8
        fEwpriHJrTUV0IICCEBISAMH+H9TSJafGo011yMh2qLnjdn7F8YhagnwoqpzoUoSWkqCH88eIHk8
        H1/dNJjkptLo1yjatke1L2WaZdbfl2u5liWypaltoSBtV/CQcHByfP0rfinaMmSKQS7JbzLuWbep
        mCuXbkhG91nxrRnAVkYz0xn5UGoht58MLDK+C2VXedCKQ9AhOgj/ANJxYP8ApWPamaboXRrC0LT8
        PMt5BPGwjf8Ap1odj8E3jK4HTTziHG48RhSuR3sV3k/MJFXHcU2gbcbbZrgz/wCKhxXdvKQ2w+kH
        6kUyLkumC0n2hidR2zR7KUI01EcQf/TTHK8/U9KJQeTyDuUPBh/tMsC4vxyezQ7h0XtSEn6gHFWs
        TutxPU87Rqx2wWVwHv8As9fQPIx1g/nlNW8D8SB9b8Emt/ZbHtLQT/bCeP4kqUCk/SlPNfgasdeQ
        /FtXwLHcsz1PD/GRz+VLc7C20B7rb5bysC3peV+7u2kfqatTRTRHJfZ/rq8OER2IcZk+jbZ4/WmL
        NCIDhJjdjsNeD++/31hlvzDQwr+WKv8AUv8AtRSwfLJBF7JezmK3j45cleOri/6CgebKw1ighhP7
        LtNKUfhGwE/4SqrWWXllrHHwj1r7OrJCe3u9+sehUoD9KCc3I14XsJvaLi5oqTFvuim1M3S2vJlJ
        W3uKkpRkqJyfw46+1cD63oIa/SS0+dXGXDPXf05n08tTLFquYyjt/wAtIkHat21a37VbVHavSIsS
        1MSFKQ1Eb2NqfKQSpXOScEnPua8J9H/pjTfRb1GG3J8W3bS/9H0z6P8ATfpn0rXy0WOTll23b4VP
        wuexzpPtHiX2xJ0/cu6RcITQa5TjvmhgJUPXjrXssXvSmj5z9f8Apc/pOqliaez+1vyv3+V5I1qV
        TMVTimY7bSCD+BIHNdHHbPMZKRy32tyGkSkPqXhJcwfzruaZcHF1PyR+FudaKI8tKi4jJSrnJxT2
        67My5IJqNh0SXCGwkk9EnimxaAZYHYWYMe6NzpLCHHI60lIV0Sc4ycckVn1NtcD8FXydBXPXcFzT
        8iIwlpp1K0rSnhWzIUP5Y6/0rFCDT5NcpquCn9TaruUhMjvXQUu5KktjA3DHIH1HPsK34nXBiyNs
        Bdn83UDusviNOsrU6lJ3oTnxI8846c4rRlcXj9wrHu3e0u5uP2jXbDMiCuMlY4dQ6okf8/KsDeOP
        Rq977JJY9JajtSBIXNMmRj/9QApP5Yz+tLlkjLwGoteRO43LXdvCzutygen/AIXpRRUH4I93yV5q
        PUfaArclyeQ3nowyEkfkM1qgsa8CJufyQ95zUNyc3Pie+odNwWqmb8ce2hXLHTUnVzTBjNLnpbRw
        UBBwP0pfqYLttF+8it/1FdLbK7h9E8nAO5takkk9R0pqcX9tC5No6NvFxuT/AAwggK8lHNYYxS7N
        7lY4tOgbxd20uy7o9HCuQEkkj9aCWWMekWoN+SUwOz96ygSH7/JkNp5KFIBP6mgc9/gJR2+QkdU2
        y3p7lmO4ojjkgVaxX2TcIftpm5rwuOUp/wA2f6Ve1RKtsdsRbSocsqB9cCqbLNnmYLaTsI+RFUXd
        AmXGjvZBUoeyVEUX7FqQQ0ZaGId1lPbVupkW2XH2OL3bitvAHzrnfVPdiUfydr6JqHg1Ucvw1/3Y
        60JabLftGXe33OEXYwllYWFYW2ru07VD9a4eJtRj/wDeT2/9VZHh+sTzYW1ai0/48fgqPVFj1HpK
        b8WpLzaIruWJqAFJUk9N3pkdciteKDxycsfKfgdk+r6P6/pYaT6hJxyJrnw31d9c/DHiteMaktSo
        UxzuLilH3iCnhWPNJ8wa6GGKvdHlHhPqWjzaGbxZ418P5XyjnXtWWqS73aFFamfGR6/Ou5g4PNZ3
        ZF9OqdbeS4VrGf3SegpsjOuzGqIyVLL7ZxnrUgSQK01qFzT9xUoqw094VH096OUdyKjLaydm83OU
        htDEttoyOVLVyjb8h1rO4pdj02+j0yyXm4Mj9nF+W6sBLm0DAz64/Dz5VIySLlF+ApoH+0vZxfJN
        ynpQIbjRafSM7kq4IOfPnHT1p2SLyYr+BUZenKyyLl2m3+2RGJ7hWy1JQHGVpXlKkkkA8HjlJHPp
        XPjKEpbV4GyyuKtjGL2y6luajHZuqEAkIQe7H4vc9cfL0qsmNp2ilqL4YGuHa3eWSv4xzv0pCkqG
        5SVhQOMYJPnVx07l5KeYFXTtdvFukpbgtthlYyHQT48jPn+VSGljkXu7KnOUOV0Dbn2qaldyhCyU
        kD8CvCfbinLSY0JeaTGZ1vfH2lOF9TXhyeNpx/Wr9CCKWRird4kymUmbJCz1CioGrUIrwRzbOm7k
        3BjZUl7lPNAmbegOdZORpKEqlOAJPVBwcVHjTXASm/JZFq1XZ71bO5XKy5twSo4NI2OL5GNpoAS7
        Qyt/ejcpBPXdmm7uAKDlrtMKO2HFu7AOcqOAKVKSXYSQrNvenYDXeOz2yPVGVD8xxSvVguLI2kRy
        664sjKVFg7gBncCMH5c1azx8IFyRGH+1a1wiXXoIW3//AHYUfpto985cRQt5Ej1n7bbSNQw3WUFh
        tteTnoUkgHn6+lI1GGeaFSRq0mpUMhJez7WqYgv0DvlFHxKVbG8f4gc+2AB9K5D07X+We1+s62Op
        lhyXbeONv8q1/wAdMQ1XreMrFmkAOtrRsUpYG1Q5rVhwv7jzmXMvtKmuNisbjypUG4PtqbJVhLpw
        2PLFb8ftfQrU6vPqIKGTI2l8+Co9VyO5nPPKcD4JIUonn05rqYmcXJ2RmFNU0rwNE56KprQgc3O4
        F1Hd5JBTjBHShii2yKXJIyo8U1A+TrD7LXZvpa/2FvUfaBampUNaUphNkqUVJTkLJSOBlQwMnPWu
        bq8rjLbFmzTwbVyXBcfaHqHRdnhjTmmdHx7enudodabSQnGCM4GN3Xjk8fWs+KMm9zY+UopUkc6d
        oOs7W0X2ytLqnRsWhKhhfl5efU5H/Guxgm0qfRzstNkCnT3JURlltSu4QPCleTkE5yf+FZnjUJP5
        FStoaw3nYq/iArAT4jwOKurBSZlCFyVb3hhtxQ8ZVjknzxR1QSQPutxbajIt77CgtK0rDy3AsLAz
        wPQYxxQwj7nJDckvYkNkXOI0UlEltAx0HyptMRRmRqCG8pIcdSUIGPCDgn/Wh2siTFIuq7bGQQdx
        CjnCUjj9ap45BUdW3AtvtlS5bTKFHaFOr25PpzWD9RBPjn9joNEXfTb2SHZUwJz1HUgZ4Ix1FE9S
        39qB4XYxm6ncsriXIj6TsIVtU0cKT7jOatTlk4BlPaNHO2zU0VZdhptmw5GVNKVj6FZoXpt/EpMH
        9Q48pAeV2x6huBLMZYZccPO11YST8s4FWtDBd8gPUyfQGna9vkdKlvyJS8januvGSv8Ah6+Z9KY9
        LFdAxybnyNL1qS+bm5MeS8PuwVsPABxHAynPn1/KrxYoNPgHI3FgFd3uMwrU/IddQngJUvgU+MYx
        4oU2xJE2QwlSm3DlpRPdnoQRhQ9s1bSYcJuDsmFs7RF2DvGpBcLy0pJczhTiccbh/EOh9xWOem39
        HUjqnFU2NIPaBcb1fCpS092SClJPHzNE8EYQAWeU5Cur9WxUMt2u1Olc91Y3bDnA9OKmLFzul0Vl
        ycbV2RnVuy1WJDUpaFy5XiI8xWjG90uBORbY8kNt0hfdcHlJxT2IFH33CcqNRIgKmrK0k0SKO8fs
        m6Xjyew63yrpMKVOPSHWTuwUJLigAn0PBOfKuPrJf63B0cCrGMu1K1pQhbbU5WQCggqwSPpjjAo8
        TAydHKurkOsXXLzhUjBXg+2a6eMwy7AR1qoIShEJJCRgb1f6UPpW7spqzVGu5iM7bfGIIxjnFF6a
        LoayNZ3V4KSEspSryCc4/OrWNFUBlvvOqKlOLOecZOKKkX+DyUKVg848z6VCWLlxLY2lOU9UnzFD
        RX4Ew06rKshseW44J+lXwSq7OhnO0GQ/GceTBlPMqeADqgMhQzkjnnnP1rkfp1F1ZpU5SVg+4ajn
        3l9TjU7bJaQAtLqQlY43EHzzT8OFVXgz5ckk+SLuXia684xNeLzYO/AUep960RxxjyA5OQwCEKkK
        U05tTkEYPWjdMpDtuXFcUVOcPJ8Ph6Ee9Xdrko3iXhVtltXEkrREcS/gkEHGPXignDfFx+Q4PbJM
        ZKvRui13SU4pTjzqv6cVIwWNbUVOTlLcwcmVlK0pSFblEZz0FEgQzpmKi8ahh21zBDjgKwk/up5P
        6Cgm9qbHYob5KJONcaEh324SJ7A+EdQhJUUYAUeBnHkP+NZ4ZXjir5N08KyyfiiAPaC1FEcUmE8S
        Vj8KkKScfTNOWaEuxLwTj0D27NqqxSPimbclTmPCpSkq+o5o90JqmwNs4O6A93cus55Ui571OE4J
        Pl7AUyKUeEA227Y1hd5HKtw2oPrxRPkEVllTailZwRz8qhBvMst1agC7O2+SiCpxLQkqaUGytSSo
        Dd0yUgkeoFEijub7NkpLvY5aPvAiPGZcSokhPKXFk9a4+qj/AKrN+GT2Eb7T72Hi+GVnKVrBIBx8
        v50zEheSRyzqqY8uTLWtzcoKLSc+/wDwrowVIyN8kQ5zRkPHAFQhgDmrLNkk5x6VChQAqISkZJFC
        WKsR96sqyQnkkeQqm+AXYmpze4paxnJyKJcKiMtZp+O1b0/BahIdSgOqYQD4Cf3Ug/hx0yfWuek3
        K3E0WkuGb3ObAiXA7nlvulBU++pYJUo8849DxnzosSdWIz9kaMtb7riN5wB4Tnk/85p4gTMwoWhr
        O4r6EeXlV98hI1E1hXJcG7rkfyNRlpDWbdYpjoZU6nB/Ht8R2+mBx+tXFPwEogj9rLZUr4NOEg8F
        YGfyo9l9luNjYzJbgKQ+oJ6kJOBV7UiVRYn2frBL1D2gpDDigIcR593n8QxtAP1V+lZNdlWLFbNm
        ixvJlpF0XeJGQ/8AFvoWtmMgKfQ06pPfnrtOOuOnzV7VhjJtV8m6cFu3fH/Jvc7FCXZU6hsMoOLU
        8hh6M45lSN2eo9OMZxilxySjLZNfyHKMZR3R7FZMa9WW5Q7X+ykfHPFtcZ1DST3RzxgY8vSrjkhK
        LlfAMsck9tckD1Lpm42qNcCmzsuomZZedVHSopIXuJSf3Dn0rXjzRk1yZcmJxTdFezUTpcRuxORA
        3HZcU62Rt4Woc8gZPQdTWyLV2Y5XVAyfb3iyp5yQ73qwUqVuyT5c0xUAWTPlXK5WSdoHUhdi26XA
        i3CAVNhGyS0yNvpnchak+f7lFijz+5JSOnPslaLlXHsfs1sTZZcsOvPlx9jugmOS8rCzvWkqBGPw
        84ri66bhmZ0dPFSxrkBdv3Y3e9GpddkS29uVYKMYWM5zjyx0Oc0WDOpdoDNirycWalIadWHVJWpT
        xPGR06/zrqwdrgwNckeKuCSODRohqT6VZYoG1d3vOME4HNQFmmCOM9apliiN6VApPJqnySxdlQCv
        Eo5/g9ajB5ZgRmiSS6sHPOE1dWSyVPyFyH3LlNac8agFF9YB2gcdepGKRFKK2oKTcnYOl3eOkLUm
        UhZcHJSnnzotl9ANOQOcvRJw00cDkZNWsZFD5NWrk9IcKXl4B6Y4AotqRbjXQg6+nalJXuwScDyq
        0iJDZThOcGroKjwJyMjirIb4xlIVgHmqso6b+xZo2TfDqe6RmFuvExoLaUjJIUVrUP8AdTXE+s5V
        FRj/ACdj6VC3KRfWsOye63cSG2oCoQhJQt9SGAd5x+FXvuAJJ9MVyMGr9PvmzrZdP6n4Kh1ZozU+
        mXUTn4L7cZAGJDaCpskc4Pofniupg1GPKqT/AIOdnwTx8sl+l+3SyPX+y3jXemRIdtK0jv4CUkup
        Axygnk/Kl5ND7XHE6v5ChrKknkV0Pdba17LNQaZvosd/7h9+YZDEJ9ktOEKPIGeOM4wDVQwZoTi2
        uCTz4pxaTOc75Bb79xcZQ6kA5B5HNdfHJ+Tl5FfRGrlCekp3ddwwPetCdGdKxze9cag1TOYlaimo
        kyYTSWmlBtCMISAAMJAzwByeaJTafIWy0fST7EiH3Oymxy0xghLwUsIA4OVHnH61wPqUrzto6GnV
        QSGn22ZUNixzJW1La0NbEpz+951WllulRM6qPJ8sr+oPTQCckJyfmST/AKV34Lg5c+wV3JUspQci
        jKujVTS0jcRxU7JaZhKcnJUAPerI2bAoCwClJH1oSCneJSSG20gepGTVlCsSSW3twKQMFJJHrVNW
        RcCzqu/X92AAP3gcZoiugctxZUVLUST1ycmhSCqzRSiaII8MnioRmwG0cg4qrBuzTzyKsI9g1CGQ
        PaoyhVfdq2lJwrzz8qhS4PoT/wBnJbYlv0gvUEgD/wCJS5R8Od3dtIQgf/MTXlvrcry1+D0X0iNY
        7+WdZ2+zO3XS2oro0FCVJbdKW85HhCen51wbppM7D5ILf9ISURYNoWlaUzVslxLniyFJJ/nnrRwl
        UtxUlcaKO7UPs+2lr4K8W9j4RcuKmSv4TCAFFQBOw8D5CutptfOKqXJzs+jhJ2uCkbp2WXofEyoM
        tmUxGeDRbdSW1AnpxyOvWurDVx4TRzZ6aSumQHVNivDTi0KtzaCz924ptwHKh1Na8WSL6ZkyQkny
        QSTFlLWWw1uUkkcq6VoFICLacjSd6VI3A8hKs1H0aoRTPtp9gPs6vsn7LWl9aaiuEW3SJzLzlvZ+
        AG1qIlRQ0pWVAqUraV54yFCuB9QyY8O6cuxsXOWRY4KzmL7d7V6ZhTVzNRQZ7cfc6480wWVrGSMb
        QSk/nSfpeqWef20dX6h9Llp8W9y/g+cMyX37q1kZCiSM+lepiqPMTXIgl1aeAetELPLW46PF0+VQ
        nCNMbeuKhdngU55TmoX2ZUUpOUHqOnpUBMBRA6+1QgoHNoAPNQrsRyc5VyfeoGZTtUtJcztzzj0q
        E6FAyELUlwEFPlQtlNialE8k5qyzAASfFzxVkZjHpmoQ2wcZPFUSzKNieSncahD6O/Yauto072Hh
        Vyf7pcx50IOM4BcWpWfYhI/SvKfV056h0ek+m+3ArOnNO6igxdOOiNLCvjG1KQndglDj4Sk8+RCa
        40oO6OkmmELhcbcNUQRJaU6mF3SgrjCk7VHH0oUuAmyqu0SREu0q0R4yErZAWjpwlCHikgnzIwPz
        rXiVRYiXMkU/JtjdvRMNxltNd7KZUttWCrhfl+ldKPKVfBikqu/kp7XcOOm6PxIiCsKcUQUjPGSr
        +oro6d8cmDPH3cFGavhOwr5JZB2bktr2/wCdIP611MT3Rs58ltke7P7Rb7zrSw2i8OlqFNucWPKc
        zgoaW6kLOfLCSeaHO3HDKSXSZqwe+aivJ91bv2odn7+hIsDQ18trNhtzMhmC2w8lCO4iNhASkeY3
        cV841eXLqcnvTR676ToY6STyS5dL/LfP+EfOX7V2oGpMZ6O+ESkBDTcxQIWhC3UFQQT/ABc+XSvS
        fQsaU03+RH9Q5v8AScY/g4Z1BZl2aaWk7lsuALaWoclJ5/OvVuO08S3YKSDnpVAmCFDjmoWewTUI
        boYfcwG2lqycDCahLCts0lqC694YducWGsbz/Dn1oXNR7Ik30ER2eX5PDjWxQ/wKP9KHemSmZi6B
        u8pxTcVpTq0jKghBJFVLJFdsii30RMEg5BpoRkY86ooUDxcc3rOVeZPnVNFNGXEoAABJJ6e5q0Ur
        Mdyo+JSk/LOT+lWS/gwtAQMk81RadmFqOQBjOPSrIkZC8jaodPOoSq6OvuzCc/auzu02cywyldqa
        moyraNy146/JRNef1SUsrlXmjvaWW3Go/ixjZPtDTY/bpGuL9wc/sz3KLAhoueBuOD927n2cwvPp
        mmT+np6Sq93YqOurVX/b0dX3rtJa0+ESnkLTIlRVM94pxK8OZykj0SpKjj5GuBDE5nclkUSCRtcq
        uWmnodycQ2/b5kxRc3AA72goY9MqaP51q9KpcGbfxbAvaFMtN5tSL1HmsF1zYFNtrBwvulqH6p/S
        tOG4+0RmpqyiZ2okxnVySvLjrJaUDzlRJwfbjFdGEeDnTlTK31bOF91Mt9uIplSW0Ry2DkqKEAZG
        Bnnj1roYY7YUYcst07GUqJ8C+2UAgjGSMcEdeRweR5cceVP+5MqMtrJVC1peltlLU5SENtlIQjlJ
        z1+WfOuS9PDyjp/q8i6YLnap1fqG3qtcmG6YCXi+p5JOHFAEJzk+WSOK04sMMMtyM2fVZM0dkgdG
        iDUUV60SRvlJbUppWem0ZGPpn6V0o1NUc6Q2Y7M7itpt2UCgODcCFDp6+tZJZKk4vwGsbqzLWhY8
        WUliRGW8pXROT0+Qq3k4sijySVjR9jjvhLmm+8SlBJyTyr/MPKlb5V2MpGJNriQo6UNIQhtXT7vC
        k/LrmijN90C0ug5YYGnIdsVJkz5sacr93kJWPIcDk0rdJy56DSSXBh65RytaG0PPjkEKcXz8+lHc
        UByM4a2fjlyZi3YqHG+Aysk5yOp/56UvK3JVFBR4fJRuzOea3C7F1R2G8BT5WraCQgZGfTNQG2xH
        PklA5/OqLo1JJPWrCFm3NicFOQagDXImV54xioXR4qJUV+dQvxRgAqUBjk1CHV/afHGnOydqZbvA
        lm0RYO8HnfhKD+oVXC079TUbX8tnZzL08Fr4SOeIiVPWxhxPXYUk4544rtPs4/g6v0dJl6o0Xpq5
        yc9y1DQ24tRyVqSV7v1JrzOdLFlnFfJ6TA3kxQkwuLAzc5Ua0MeD4gpWSo4SfArGfzP50Km4q2W4
        p8A292dLBYZjBQZ/9AoGEjBUPqASfzpuOXdi5x44Kv1Tp6VEQ1ILCllwDGUnxEGuhiyJmDLBp2Vp
        c1PQ9RSe/SoKQ7kgZyMY69Pb/WuhjdwVHOyJqbTPXCYqc6wyhSytaEI4GBnGB+QIH/Cm3ti2CuWk
        G7TpO6R4xeUFJZJKF8dPf+X51zpZYtm9YnROey++2LT1om2fUmi4t3SZHeIkkJLzQPkMjBTkZ6jz
        rPqcGbPJTwzr8BYc2PD7csbIlrpu3wNQrvekYkiCwpQWG1Db3a/PbjgJJ6Dyro6R5ccUsj5+THqH
        jnO8aolujbpZr/F+MW9HiPkd3JSsbg2OfGlPoTj5GtGrx+tj3wXuXj5A08lCVS6YYucS0RYKHreI
        0xwKz4WlKdUMeW0YAJzj9a5GKe988G6cFFccgg29lxxuWLhAAdY3LiqccK4688bhn8XsM9acsr6p
        /wDsV6K7sj9xKZM9qA3IbaWFpStaoqk92c8k55A+lP3rbbEuPuqwhd7hPjgJbVAcChtSI6TzjjOP
        OpjSfn/JU7BCL68VORu5++3AKwSCr6+1XNuPYCoK3HTM+QW/2pDdjqKd6O4G8LSehzuxSY57+0Y8
        ddnP60JSnIUCfSugJts0Kj61C6MEkYxjioQwKhZnB9ahVnsAVCHj6VCdCsMhEplainCXEk7unB86
        p9Fplm6l7TpepezRnTst7fLdnF51CRgJQlSikD28X6Vix6dY8+9dUacmpc8Ox92RqyoeTaQ262pG
        1w7CRjIPNapO2Zo9HT/2ep8GZ2XXO2vhbrtsmLcDePwoVg5+X4q8/wDUYNahSXlHd+nTvA4/DJ/q
        TUmnNHWVvVAUhZtk2E1KZzhSmseJBz57SDWbFjlmls+UzTmyRwrd8NDZN3t402mS13bzMlTiW1le
        coDnX2GRRuDU6BUk4WV9fIy57rjL60pSwlwt89RtzWzHwjJlVujn7VMmO5qSc5GWpSA7sGR1wME/
        mDXYxJqCTORldzdCulURp2rrU1M3tsKkJCtqCtQGOu0cmpmbWKVfBWKlNNnRWnWNHCDcYmoNQx7c
        VJHcIlNONlfQ7h4CEk4xyRXDlHJw4ps6yzY+U3RCZkGFbZphwrtAcam7kl5tbbqcZ4HXCTnor3Nb
        cE7fPBlzJVwALnZJsBe+ftuDC8rMdte7Kc43Db0PzrZKSnH2yoxU4vlEWlRUWC4B+2OvORVq/C6k
        pUtHXafcdD+dNwZW++yppLosVGoZZZTJtqVhh9pGC2NyuQMhQz1/4UnWaS36sFwPw6lpbWJT7rZY
        ziHVF8lOMlbJG1Q65zWSEMjXQ95Ma5sG3fUMF6UbvbGggpc7tKXElxDo4JBzyOfPyzTceOW3bJi8
        mSEnuiPJd/hsJaW8Fqk8KU20UlCFc+Y6jp1qRuuQW4oARu9mXuPITHW596F7Ug7ljOSCR/QUU5px
        oWl7rLiYuUW5HdAmx29qfvGZK+77pX8IKuVce1czmP3Jmq1LpnOcDsW1RIShy4PRoiFICwkL7xZH
        yTx+tdWWtxrrkyLG+w0exeAiMXH7o4lSEnJStPi9wkjNJWtk3SRW1IZXTsfiRkI+Hv3jUBhLjaSS
        fbBH8qZDVuXaI4pAGb2byoqlpbuSFEfhCmiMjz6E4pyz34KdIDy9LzohV98y4EnqCRkevIpqmgG0
        D3IL7bwZ7tSlKAKdozuz6UV8EsJWzSGoLs53US3OEjJORggfLrQPIo9hRi30Ho/ZLqRxoPOhtCT6
        qAP60Pqx8F7Jd0LwdBtMPBqXILZKgkr3AoSSfMjOBVTnJK0ilHmmGb5ao1thJixp3xTzZyraMoSB
        xgK6Ggxty5Yx0uBxoXX1z0gzdoUFakpujCWncDjAyePnyOtLz4FmcW/A7BneK0vIL1LrG43uw3KN
        cXyp6ZcmZPCzjaG1pKRny/B+VFjwxxzTj4RWTNKcGn5YS7M9cXCzQ5EV6S6/HfbUwWysnaoAqSU5
        6ckdKrU6dZKa7C02dwtPomN81xDZnlaEFTyYexQVjAX3QQc++cms8MDaHzzJMqW4OCROkvqPLrpW
        B5YJroRVKjny5dh3s7lR7dre13WYpzu47pdX3Z8eAlXQnzzihzf7bJj4krJverlKuch1+LGu07vF
        K294gpAJP72M5pccsUqJKDfKGNrttyalPPXCCxHVtC+7U0ptKj5AAJPJ98fOk5MnKe2y4ccMVYvl
        0D/eNQVKI8B2Ap8+h4wU/MVb4XRalyaXORZbnbHIspkNSgor7xvx4Iz0waKKyJ3RG4tUR7TV5Ysk
        x+A+658I5uwSMBC9pwceldLDO04yM8lXKJNrKSm5XJU+BaJNvsk11Qiocyso243IDn74G4c+hHnW
        TNjeFXAapbuxWNctKIKY71tS53aMLIQEqz5HGcfnWSDkl1YxuLMXeZZlxt8W0uK75AQ2t3gJI804
        olL5TKklXA2025eFrMKK8y4sgrQMDck/whRoMko3aVIKCfQWmQdTSVlmRait5GFFIABAPmeaZGUI
        q0W4yl4Al77UIrUsGRaH0BvCkpjOp8JxyM4AxSselbXZUpqwXK7VreUpS5DkRQlzcgtoSpRHnyTn
        imR0tdAOYwe1pDnRS/bCoup8GV5SUc+mSOfajWJxfIEp8AWRfpch5boecSF+nHPpTNqqhTbY2klS
        Pu0O5LmFK5zyatckRKOzWyvTZsm4Ku8aEi3FpeH0BxKt2TwDgeVKzPhKjTp+G2W3aIU+Q8mfH1NA
        AQTsQy0y2Vg9cpByazSUUqZpjKV2h7PsVynsOvMamgoU2rlLkdtC1+6TnkZ9DVRyRgXKMp9shFy0
        i7b3P2gmTDuDiXfG2VhOMc4wDz8/1pry+p7W6EvE1ygl8ZpfVNruUKe0xabgtlXwjKEd20twcgle
        cDGMYJ5zQw34avlFup8dFLkOtuKb3DduHtitzEIZXBlzcCvJwSOvB4q4spmNOOlE4w0rwHsEfMdf
        0NXLlWXHhkouoe7xTjqxvWfFjrx0/wCH/SlxSSCbtkfkJIcxg9cn3piAYQ0vLLd7juqj9/lRBayR
        vyDx+tSf2MkfuRdsZrVOnFs3CRYJR3DvWGxILJayOBgYJ9a58XDKvaaWpw+4Z6g1/qFx9F0lxnI6
        VI2lLgQoBWeSk4yfYZ6+tOjiVUKc3dg0Xa5uwJE2FBCAp1LiS6gKUog5yBjgdeBxVJ3Ki6pWKPS7
        rdA2+iww0zXApS1BvCns+eM4HyFCskouvALjfIMVpSyOInztbzptvTGaS6yLfDbfW4reN6FIK04G
        3OFZOCOhzT4ZZt3QOxLsSka9tN4tI05bbMqHBiXCZMiIcd3KbafLYQ1k84SlsefU1tx1OLjPmxUu
        HwE7N2b6klQ2buPg3I7uPChYccAIzuISSRj3/Kua8kIScPKNCxyasG3bSV3adUtctDaWhsCV7skj
        0JHSncTQLi15GkS9SLW+WGmo3egDLiglZB65BPTpSnhp2yKbMydRXa4SHVuSV5Ktx7pPOfc0e1x6
        RNzZBbg4ozFtF9Y2JLYDyDlXmaKPQMuwXc4wd2htxIKgN3TCR5CmRYDPW2CqLJVlSSC2QCBjnNSf
        KBfIrjxDdjjGNvSgSBo8XA8s71KATwPLOKJKi0iYdnEV+9y5jqbaiU0x3ba2yvaVKwcY6+9LypIf
        iuy2W7BbkxVNqsUCM4rlCjIKvF5AjbkgZrNtZo/FDXTumJljujN7u0dqZFRIDrrTZ7srSnqlORgd
        P9aXqMbyrbB0HiahK5Kyb3ztf0lcEot6YLsCW2gKQ43Db/CR4grbnPGOf0rFHQZcXL5X7myWsxS4
        XDBTrVsuMdm+MbJMFxRRvTHUkFfXBGAPPrkU2Ecn21yLlKH3XwQnUfYFrK9X6VN7PoMa9QXHQe6i
        y2i7HKhnattSgoDOcHGD5V0YZko1PswyhcriRvUXYtrqzwXn7xambaiGkl34iWylQI6gJCiSfarj
        qIN0mVLHKrZU/euRZDclr8TSwoZ88eVaxPRa13tpu0CJc4TO8S2E5S2M4VjO7nz6/l7UhOuGMatW
        iBykPhZStKkqz+E9flTVQDGjbqo7gdbWQps5+tMTKaLMhdoN4u8SJaoEtLRZbISFEkdOSB61nljh
        je6uwt0nxYsIrqH25l2n98hrBSFDJAJ8h0Hnzigk9ypFrjkmkbUDs6K45HsRjtoUEd8hkqKx5KOA
        c+vWs9JP7h1trhDe1X5diuYfvdrmSElC0pcaaUlbRVgbsEYIxnpjrRNOS9rBXD9yHdyvOkg93bT7
        TrXdHvHHmi2XB1wpKsZxnoDmpDfJc8FtRRT8u2mRdXkWKEssPLPdndyOffy+daoZFB8sQ430WFHg
        wbXDiyDGvMW4NtID3clYAeA8RzkYznjypEpvNJqStDVGMUq7Noy7mxteu9vXdYilgKamv4cSCfJY
        JGD55FC0r9joJJte7k9cb9YbdGRCj6W7txYIQhzu1JQT5gjxH5n8qtKX3NkbiuKM2XT7EqCm7RtV
        sWV51RbUwykJWQPM+IAjPsKqWa3tcbJHHxalRRsVi6XMCQ1b33EZIC0tlQKvP51uUaMrN1xJYeAe
        ZcQBytJSalFCxfLZWXgnABTuPmf60DXwUbQ4cu5LUWUpaAGSt0kZ+SQCT+VToJRJPbtBMTG0PzJZ
        cRnK8ApAB6DbwSfnVOaTDjAfw7FqfSrinLUi5MxN+VFtlaUBWOD0waGbhP8AcuO6BOtIWK1apkEz
        u0tyFNbTktPtLQ5n+FBWQCfbNZMs5Q8cD4RjP+7km1w7MLZaI4nXTVUu6xGR4MO92nHXGB/Q0uGS
        WThcDJY1Dlshd4ToWA+Vw3YbSij8SFZ2Z8uc5PrkVqjjlXJnlKKfANY17dLTfIk+wz35DadiXmy1
        sQ82BjaoAYVxx+Gqnjg4NeS45JKVnu0dce4ut6stMSVFZdXsWh5OxSCMe/Tng+lDitray8lbrRGo
        81yYy82/IPdBpalZPGAkk1bjtaJdor4Wt+chp+A0uQl4kDYk+HBxzke/XpWrck6Yra6snuiL04xb
        0Wh8sqft7pR1CkqSeRgjhWDkelKmre5BwdKmDtUQQ1OfUVhSVgPJKfPceR74Of8AnFFBlSQhD7PN
        Yzrc9e27C+xb2Wy6qZJHcMqAGcIUvAWo44Cck0XqxTq+StrqwLb3FW+YzcA0HY7awXW8nlPn05FO
        q0LLbkwbU3CRMt7EppLyA4hS21eIEccgkUtKL+5EaaXDNNP9ok/TEMWxIfcjJW4re0VIKgryWFYy
        B86zZdMpScojseZxVMIO60j3HdICJyGFnxI2d6kH065xSlHbx5GXu58A13UlhVAVDmIfDqVKIV3B
        TknyyfKmq7tAOkqYHa03OeYVcoywyxI3LQhfBIHUg9KbxkdoU/aixNJdozd5tzOk71Ze8kw2A3HL
        DQU48Ej94k88DyFY8mB4ZXfDNMM3qLbRH7tLamzXINjiOW111RUUyh3SQfLCTWmL2r3cipU37eDS
        1Wm525chwzxIfkgMl7u0nY2DlRTuHy9DQtRnTfgibQ6eutzgJDq1QZTLhKU/GMBRSR5hScdfSr9N
        S4jwTc48ib9puc2PDvlk0gIENbaH2ISnUglJHB6dCORznFbXJAU+0Rt66OxX3UXXSbLCivAc3KKA
        PQgeR9c54oW/gHh9isHs+RctSW13VFwRardOXhMpLS1sMgngnjIBOBnoOtJnNzVRCUNrtnUk/Tdr
        05ORZb1Gim492ywxCgJbdc7oAbVE54JSOVHrmue3KXK6NyUYqmS+0XSz269OWLUFtjQYrEfLTc5C
        m3nE5GeQSMjI8se1ZpKTjui7GJxva0Ce0LVulZCBDslvW6wDgLWylSU465xgYBHr5+VHhUlzIHLT
        6KOv8Fbz6FuWdh9L5V3bccJVgevnux/mrowmqMEoc2Qm+2C2zI6W2XUxlISVKKF7Bj1KM4GKfDvl
        C5fgiNqnRYD78ZUKNcO7I7t/GCrnyGOaDJGnwFF8clv9neo9CIhTVTI79ve2J2suxCsvKCv3dqcZ
        x7iseWMrSRqxShXIx1jqzTOo46rDEtkjv3i4e8KFJ5wTyCOOmOKPHCUeWyskoy4RUMT4mOtyNhal
        qSpshQATggj+tOnXYuKYnc0uxLa6EBTe8BITnI69PTFDDmQU+iV/ZvvmnbbqqZYdUadt14YvcYtt
        Ca2VbXEeIBKkkKQSCeUkHKRRahNwuPgXjaT5OkE32x2aI8zorQOlbHMS2UtzxbUyZST6pW/v2njq
        ADWJNv7nY1v4K/1XAu+t4sC8aiu0u5S2MRnlPOFeE9Bj0A9AOKOE/TdItx3IpWz6NuDdymR5TqWf
        hXnEhsqytZBIHHQA+/5Vv9aMXaM+1+SZd/f4UeFbQzGkRYsdDKGu92OtJ28JUQThWOefIiryJxl7
        emUnfYPvl+mO21EddqVHcySp4LSoLJ6AjAH5VcXKNtlS2vobu3iY5uD1uZTnaQhC8bCOcdOlZ46f
        i0zQ9R4aAU2dMuk5uHIC0t7sbEKznPTmieP01wA8jyMua5WpqBaIbLi230Mwm2kpQPwEDkZHGcml
        4ZMuaTIbKs8lh5m+WFT0W4xVBaVN/u4PB960SUMi2z6FLdB7o9jC+6q1LdJXf6jSn4x/w7u6CGlp
        +QxyflSNjwqo8oY5+o7l2EF6Q1ja2A7a5ZLb/iCW1kEpPUpQrgj6VnWphN2zR+nyRXtHNrsGn7Y3
        svFlmyVqzlTyCkbvPACsetE8u52mB6Mo9oPWPtK1JcdPQ7Td9Ih4Q2m4qHmkpSooSkAAj5DFbJcC
        oy4poiGo3LtKfKWrIGG1klC1upVtHuQBx9c1e+hbjZGWn5zS3Isu6rShLoGxKiWyU88Dor6UvJKT
        5SCjS4s6BmfaVt9/NlnO6VMa4WuBHYkympSB8YtpAQFhBQAgEADaMgHkVili7/JpjlpJfAi92ysz
        FftixaTvTtx3qUXVPBaRnr4sEkY9vKlrHXtk+AvVT5SHbuu3tUodYm6Ru8eatPerVlsNrcAATtCt
        uzjPrnjijjDZz4Kc93BEdVXi/QYjtrVptCVLVvMlUkb0ZOcDaOPTrWjFTe5Ccja9pXD1wl3iYbbe
        0rjxHBsUlpwNIcXjAUtSgc+/TNPnKcI3BCoqLfJK7Nb+zO1yFNC7RZEhsDMh5ZLYOBuCEj0PQ1n3
        ZJJOSGVFPgXunaLBhutW62GU8pA2tOpBUnn90J68++eKOMF2ybq4Qhp2Fqe9ajs864yYrUV+el12
        GHQl3G8AlSSOBjomilNU1FfyAk27bGGv9Eq09epLrCD3SZK2iB5cnFLU9ypjapkEviswFJIzkgEj
        2NHj7Kl0SXsI0O/qXUjl6RchbmrW2vZIUhJBdUMbQVeHO0k8kHpjmizTUY0wccW3aLgmPvRZC2ZC
        llbSi2rwkZ98Gs1fAbtdjjT0+GtK2XEuBlSwM7TgZzyT5dOpoZw8hRkRDVtqiM6pnXa0uByNMcK8
        gYG4gFQ/MmjU/akwJR5ILOflxL3JhMynECQ2l5tCCBk5O4+uc5rZB7sdvwJa5oHSIkhqQ3Mcu5D6
        V94lKiFp46cHg/lUk96pkS28jGce+deEu6LW6o5UE5wfcCrtxRVW+TewwnZ8otxnQ02wFOKWodRj
        nAPnSJr/AJDiGExDEx8NcHhvWdqwraDgc9D0q/SbK3UKXK63KBH72JeZEhpJ27VI2lBOMjOSatQa
        7LckZmXOXdYkVE65OPoS3hSVKBLZ6Dkj9PakKcotpBtJ0TCV2vXmFGg22O1BmJiMNxULUyQpaQOd
        2TwfYegxWSOmUrb4NX6pwpdgC46j1g+r41y2FDLyiUBMfAz1PCsnzrTDFDpMXPPN8hVu+2Cz93HF
        4ZfCHTuWyjk88ZJ6+XpWtvdyZ1UTW860TNUufDgutxUFRUptpRSry5OMDj+ZoIxj1fJJN9kQt8lq
        /TWWb1KkR4iHCpPcNIXjnqeR5davJJJNJFRXydIv6r+yRBtyYlhi9y+G0toefgulRVjBWpWMkkjP
        AAGa50Y6hy9xrbw1wR2N2lWCDNRFgXxhiE8QtkKSpSkJ80kJBKU8AjPNOnjtXXIEZ1wFm5umrvJF
        wMzcwslTklltzGepCeOVe3FLTmlSCeyTsjt67Q9GW2a8wm2uXBokd26/HXuG3qRk4I+YpihKu6Ac
        o3RCpV7h39bjlvtC1d4FFEZlrwq9DjnpTlmjDhsU47ugUjsy1M7LRPYs7TLXUMF3YtSiOuB+H5UU
        88ZqkSMJJ8ju3aX11ZpX7QRaI6llzCVvJC1IOM8E8g+4pbcX0wkmvAXgaguMaaw8/YnmlwXElcoD
        cCc5OQOooqk1T8lJq7LC1/aGbvIvkVLZDjifiG/nwqs8m4pMbHltHN96QwWHm5OT3aTnxbTkEda0
        wu+Bcg9omyxDYmZj10dZauG9GyOnK0qSrHOSM5x+tFkg5y5XQMZKK7JNqGXOslnjqavrckvKA3KG
        JLCuPCvdyRj+XWhhiVsuU+rEdIyLhcJi4tylyJBxltK1kpBHt0q5pJcEi+eSW6hTIVCZZDKyltPi
        URt59qyp+4Y+irdTxd10tU1EhTCy8phbiE7lJH4gQPPoeK24XcZR/AmfDTG77FzvXeIiyWntigla
        QyG1ADz54BxzRf7fANufIVXZn7dYn4rEeK4tawoySNzucdMjy9qrHG5KU+y2/btSAemJxiOvwnXU
        JW4dpS4oJ2qz1yenGavJFbrZUHxQdlQVN4U2ttbDWFLKFg78+eOnmBVxmmRxaAU5ybdLouMhJbb8
        ICQAlPoM/KqnUIpIpcsl9i0BKuinIsS5suSVKw800M4GOoPn9OazuNU2MXLoeM6GvWnZzsu2x4dw
        U3lC2ZTRBSTzgnjBNFUZKm6JzHmrNJusJlycREvqmbIIqdqGRFUUZzzg55oXGWHxYW9T/AXsWgdL
        pgvSLXHnrU0EES33BtCsAhSSlIIBIPXPFSU2uJFqKr2m0GG8g3JuZiY88nbFUXiYzhPU92keJQOe
        px7UbkuK6BUXzZD9bLVYEOQ7fOU1GCAp1hplB3uYztKuuM9c07HHfyxU3tdIj1mcaclx/jYbctsp
        wQpwoDZPPGD0HuMUrJGlaYca8ov229mFviRmt8pdm+7RIdUpTS21haApBTkHqDWZ5rHLGx/Gc/s7
        akWSOw07PU93u5K/upG7ISpH4glWPJP6VT973eC4+1V5Ihcps8yHv2yxDjxVrIK0pLrx98n97B+V
        Oi4/29i5X5INCXFN3XNsNzuMec2VkOMN7+8AHQIH/Sn5IJx9wqDafBPOzvVXadqWe7H/AGtaStjJ
        LFzQ206tBGNyRlJJHsTXPzwji6To2YXPJ5RJ5HaNetPyFWu4aRgXgdS5HdUlaQOvBBx09elVHBKa
        3J0E57HTVgnUetuzy6tquUaxXW1SJLYRltkOtoKT6pVznmm44ZounTEyljfK4DmqLg03fFzkhRY+
        HaUSeNye7ST/ANKNx3QoG6kcs6vlJdu1zcZfUtp97ehCgBt3Kzjj06VpxxpJMXJ8ssvsqtN1Ol4e
        oLdHiYjyHmx36ivec8+AAK8+MGgySVuLLjFtWhW8aWuGpb58Tebi02nJC1MwyggjjGM5PB61FPbH
        aittytkvstkjwIEG6I+8UNzC1YxkoUU5Pzxmlt8tMKq5Dd/LUqzLeSg7mTzx1rLJOMxye5FG3Cat
        y6swluBru5qXUOKGQCAcce+cVuw8O/wJnzwK36OHmH5TTSY0xj8ZaUNh9CD5gny5xWmKvgQ+COtS
        bndZKGHpAbcUQnOUt8+5GM0mTcOGGvcTizaWtMSE25MiIkTHM96oKJQlJI2nFB2GkkaTNO22K6Q7
        GjtoPILp2bv8p4FMTUgGqBUpuytNnYplpSUn8T55PzBNF6afaK3UA2rlFt0lPc3JDqnf/wBp7Dg/
        2h1oMkX/AGki/kmNkb1TeYqnbG5PeZ3d2SJpRk4ztGThSqyuUov3Dkr6HKL5rNp12HJgSJSmSEpZ
        XFQ6psDjn0o/dXDB4FNMytcMK7yaFJYQD3ipBUnAI8tuCMdaHiT4YxNpck51Hpm/fD26fbxBYjTm
        kvhlxTilEp43nHAKjk4x6HFFjkuVIHI6pog9/ize7Zak2dqRMWooKRLJU9z5JUMgevNPVpWnwJdS
        ZCv2DcrUsuyIym0pJKcEYT7biaGW6f2lpqPDLH0h226gs9sbhT227rbSgMCM9y4kDyaXglPnxgj2
        rBPDLfRpjmaQQv8A2h2UsmXbGpzXduZjxn4iu9Geo7wHb59cc46Cn48d8MGU/ggepb/qG+J3SI3w
        bTIwoJbIU57KPX8vWnRaXERUnfMhaBqGwSrWqOzDj2t5GD3hLjij6hBzxnzzmpFOEvc7CuMlxwST
        +1+lGGIseM2bi+hoDBbxsc4zkrxnHPIoOW3boO0uuQhatfQJE34S72O4SIxTkCKkKyvPIX7fLmgl
        GlaZcZpupEr012d677aNQRrT2X9n92Qhh4KV30XEOOjzW4ojgnyHmakckYL3uypLc/ai4+3vsEun
        ZzaobuoWEsTlspXubXwBtxvSCPI8bc5FCnOPDXDGbYy5TOANZWtyJepaWmnFpLqlFW3jqa6GN2lZ
        lkueCZ9l3a01pKwfsr9md6USHHEPJXglSscEYOcY4+dI1GFzlaYeLIoqqLB0xq6/6muCrjZ9HxpT
        rBL7jbrg8QPVawccGsU5Qh7Wx8Lk7SJdb2b8u1XeNqeyfs6U2+iW2lJ3BSFjBI4GBkD86bCUZ04g
        5ISjakNL7JfgadWpDPfb9qVE9Eg9VH5UM0nOiouonO19uComoHXFhS0IcCsJBO4D0FbcKuhE2BJe
        pn5zj874JaozXhQhSiAk58/LPP0prTm6XCFp12Zs7N2vwkyFFQbZUEgNN5CT5DOMVbjFcFW3yEDE
        u8IFlN7ucdY42d8QT9P6VFCL5SK3SXDB8i33iQ6d19kL2nA71WefbmiS+Cm/kAXNFwju9zMfUrjg
        k5H/AAqnuS5IqDVl0e0+jv52CVIBSEueIZ5BAH9ai/IQQhqv2mYr0K3vGRFU53ndqWUlJx7cHoPy
        qnFN2ibnVBOwdr1ys5dNwtS5LqvCFqdIUkD93JByKVlhf4DjOu+ToKVqK0x7e+/a9aQJS5K0g94h
        oKO0/iGeE5+WawKm6o1NtLhkcn3G7Xa5uMx1l6X3e9l+3tB5KVDnxgKI+qenpWiO1Rt/8ipKV8Ed
        1N+zLZCjz3pb8m4zDl19xwh1nyKUoByPPk5zTYyu0+kDJVz5IK0qdMUlh+W49GCypDKnCokZ64/p
        S8mRW9pIxfkuTQ0TTEiCzd7naFl6K8kEIUoBok4C1AEbB55NZlOf22aVCLW5hO4RGoM9Udi/rmNr
        WsNPFxJcO/jGTyB6dOlNi7VpCmqdWCZ9nlQZseK+lKVNoIU2o7SSehPP6+1Em5JsXSToiWoNLoQ8
        W320iQn+8wsBSfqOCOnvzTIu++iSVA3TGgdf6kvaIGitK3C8uqUABGZ3lJz5n8IGfWgzRglbZcNz
        fCO2OyP7MPaTPtyZPada7ZZBuSosxnD3rqU8qSsjwNkgfuqPqBWB9+zlGtJpe46lk/ae7Hex/Tad
        L6MsbcGXDZAfiu4bDDuP31dXfXd5/oNMGsX+2rfyxbg5czZwt9o/7Rk3XsuXOuUxC2peEh1fmkAn
        CEfuDj5nPlTIRk5W+ypySVI5Z1Jd4d3YLEAbGNpDz3Tf6ge3rWiKcXyKdNcEGj91Fl/DsKJTuynH
        OKZNOURfTLn7HtYWPTz01y+SZEJbyGyzLbSo7FJVyFbedpB8ueK5WoxztbVZrwzir3Oi4I+tdK6r
        vSIKNSRZk6c0uKg/EhQdSU5RgHkEFI4PvQ4Izg+uA8sozXdsCz3W0WOTHnr7pyO53CgscFROABWn
        LB2pIz45cNM5q1Q641qgJdCgd/7ydo2A8YH/AD0rbgXCE5AFddUOtyXYMfa5CLhe2dAXFDnnz6Ux
        8PgXZpa9W6kjpdjwVOfDvHLjbSR/OqUE3dF7nVDpM6+Ppyi3K3btxW4vKj75NNSYvgV36iktrQW2
        CgqzlXUflVV5ROATe0TUBKpvdqAITuSOQelVNSonC6DFhEpdvQ6MOHBSlROC2U+/mMUMZXwEwk3N
        lPNlpLhU6lQ8ISPFR0gQHdNSvwlpji2sAnxHckjn5Giaoi5OxNKdlPZRqyyMwLbrmHJvZZT3sKTi
        OttR6lAR+MJ6Z4PXrXnYanKvc1wdP0oSVXyN9R/ZzZ0JcFNXS2S2S+0HYj0Z5xSZHA4StBwM+9aI
        aj1VdgPE4shErsvhS5UoFmSkxUFSy7LJWlPplQ6j2P505ST4FyiwFcIFy0KCrTsosoktEF2RGbcX
        80lQJSOeowacscMn3LkXvlj6YL0X2mXLTbNwgyLVFnKkuhbry8haR54Pnu4/KlajElJNsPFkpdE4
        i9plnvEABnT8piakJCEhCHkKWBjcM8pA4IHPnWZrbLsdvTXCPXm6TbmI8a12C5qWWVIffkONhbjh
        x4/xHaB5YHSmwa5bAl+BPSEFmNqm1ta9jR37G08XX4jLpK3SB0JI6HzxRylcW4dlRVySl0dbtfa7
        7NdMaaFl0fAtdtdbaKQhppLSQnrhAIwCDg8jPhArKsc69yNW6F8Mp3tY+2repsUO265tPoG1AbS9
        tTlIwlwpAO4+ecD06cU+GFydMCWVRVo5y1f2/Xq/sv3DLX7QlJBKlJBCM43ADyFaoYadGWWSypbj
        rCdPUf2hIW47z0ACR9KdsUehe6xmL5KUyIzSikD14NEoeWVuEUSX2ne+ZmELx+JPWipFNseR7tPl
        PJckynE7vCEhAJV86Fy2rgqrJpoabMa1pYXoEl9S257CiyiMdyxuAI8/LNBkkpRdhQVSR1lrfS93
        iacmMxWnFzJivxJCMtJ/eVg/zHmRXPjNSq+jZKDVtHIOqYky33oNT1NreScLKXQs4BxyQTjp0ro4
        mnyjJJV2RFLDTlz+Hcipyl3kbiCfark1dAJExaiRlRwqIhICABtCeRTY8ASG8l9hhafuVtrCeVE7
        t30o+QRq7PlR4yni4gJ5JwTVXRKsj8+4P3NKe+UQgKB2gcmkyzXxQajRKXEyYjjTMZlttnGFp7wE
        OD5etFCmrLfYrE+FQ+VjvisEqUlxGACPTzonyUgNrTC1sS1rQpwjbjPix8s9Pf3qmk0XzZYE+LfN
        PzXviocgKQshK0JUAhSTzg9etct4k0tpptrsvfss+1FcXYkbT3aNcG7xHRtbiSpLu16KQONyseIe
        XPyzWHNp5Rl7FRqxZ7VNme2rtT7OL2pN1sUlSJ7rIQtKFEtLwNu4DkhXFa9JGUfbIXqHGXKKBud6
        vt4O0XN1MZJCMuqG4Z9M+VbJZYw4ijKot9k7tNi7LIVuR3V2bny3e7Ly30KSSSOQkE/hB8yCflWH
        1pzdyNG2CXBP4NqsCgwu2321w2gCw+VS28kkdNvBAwePL3pbn8qxiivDN06ccjh5iI3HkNPgDvmS
        lzcgHhW5PKav1Uyem0BdRWOTFcaQ4tJThWNx3LTxyQPMY6mmQlaBlCiqtQaPafcDsi4vtIKiNq+Q
        PkK2wyNeDPKCAtx0jYoSHXUy3QltIUN6QCv1wc4p0cl+BcoV5Iv+y25K0sx1obQs4DjnHX/nrQzz
        qP2qyowbfJPI3Yfp+FbESbxqeKuW+O9QlmQlQx6e/wA6xx1Tm7SNT08Yr3PkZr7M4DKG1xJYcSs+
        FYwSD5g1qjm3eRMoUBrvpyFbnzFS4l+Qoja0hGVZz1NHv4tvgCuR5btKRpEZb9yaCZIOG2RkLA81
        HHPl0pLlJvjoYlGuTvn7CX2Qjc0NayvltW38WUqCnCSUNA5ABPI6c++PSsubLLJNYcfY6EFBb5HU
        v2pOyTR2stMPWBizQYzNhg9yuWVFl1LjgyjxJwVgAbiDkEmtWLDHdS6X/YMpy28+T4m6+sitM6jm
        2jvw6WnVICwPQmtK4EESeSsSVyEoWsrSnxJ8lYxRPh2LY/bvk9GyIiCQpWPGoknI6CqblVolJmrl
        7uxUUOLSkEEEBGKFym/BVITSiQ4kBbjru8+EBBxigcpN8l0h23YJEjDaWPh9wSoLcPh+WP8AWhUo
        9hU2FUovTIDDYYUnw7nFp8vb5e1RZKLcSUjX0vSUf9ntx482R3QKVLjkkZ53JOc/X0pThPNy+ENW
        RY+Oyvb7Pl6imKkzy22okq8CQBzWi5RVCW7dnSMu76d1BAVJv1pnR70AsyXwla23lAcOJQk4BJ4P
        HvWSWOcXUHwbIzhJe9clbarg2NhldwhyiXFDCW/4uP0NOgm+JCskYrmLATES5y2g600shSMbUHhA
        96V7U6QKTaJnb9A6mYgRJk7T9yfhzG1KZKW192o8gKKwMdQfyqe1t00guUqaJFbez68ybayt+Vao
        xKwlph3CXD/u+37xofUxRlSLUZSQ6PZg87a1XOWw0G1qKnGFbyvhW3w4zkE+Yqt0HKol7XVtASWz
        qXszcVd7Fe0oaKSRtw4Cj0Uk9RkeYNEsEM3DKeSWLlMfaTc7QO1e5RLY5qRDRmLCE98lLbbaleR2
        p88Yrn6nVQ0i66NOHFLO+WSq/fZj1VDks29ep0SZLqC+GlKUEpz5qyeOnWlY/qicdzXBol9NfVgC
        /dglwtEeL8W6JUiUjvFNp/h8juHrg4rRi1qnbE5NFspMiN70HKsW5tcchTiQpKtnB9Rn298VrxTj
        k5M+TE8fA3s1iRKuka1T4zyHCpHBHOFEY5PlRTSjFyiVBbnTJDddIaegyltQpbq3G1qbK2nNre3G
        eo6mkqcpL3IZLHD+1giVo1yE/wDHRlvNONrGe8wckeY3cn55o1kUuGLePb5LM+zp2S6j7We0GJCj
        W5DdvtryHZktLYKlEnhACiQSo4z7Zq8uTZHvllQx7n0fRmV2hag+zxpxi32a4W+7hiKSYMqJtWjb
        0Slxkjk5GNwPnS9OnCTnFcsbNKXDfByd9oT7Xz+p7PLh2dU61SZqu8uJklKlBeCkgbTjbjjGARiu
        hjWyNIRN2z556qurtyuqpHelaXFkBaj1z5k0xCnwYt0F9ONj68A5xjg0zchTXNhhLKiEvOrQFpIy
        oJ5I/WqKHcCyv3WYykQ0NsLPifUjqB5DPX6VJSUURLc6JXb2og7yGzCVHdjj8TbWMY4GfTNInfYx
        AfUcm6oU1FkQEtNE5Dpb2qIJ/wCeatKO1uJNzfDB0fQN7vU34lqY2ltCwHFOJUEtJPmrAJ/IViWZ
        N7Bqxt8koudnmQm0KftFu+H4bTLYwpKR6bTkj51shkjVC5Y2uR5/YS3htLwWuYFgFO54M7UkZHh6
        n59KW8zf4CWNEig6z1lYdLu2R3TcaUVuCTHuC4+2SwgjBQ24f3T6YrHGEnPd/wAD7ajyiq5oW/cn
        JkxssOOKP3fJ3H1Kun5CtuScqqhCpMkWmb1F09eWZbSkrj+EOtukL7wn8QxgjA8siseSTceFyOhJ
        J/g6GidvXZXPiR4Ue1Tre3G2pXEbCUtPr83OMgHHGNvNY1DJHnIzS8mP+0gl/wC0vSEe8T24Nsmz
        mVvqcakF/YoBXPPBBweoGM+orXFRaTbM7ny0Mpfaxd0SreovF2IhhbK2mE9242nnzAyCeCSCc+1H
        D0WnTKcpXyQnUt4ZvkWXcZTiETHdrbLDO4pSn95R8s4x881o9WKW1CnHySnsh1tZtI3qNOu9maub
        aCR8O44BkEY684I681wNdgyTW6Do6Olzwg0pI6Bvk2zXSxxNQ6cdn2+A+2hM5oOJluABWNqcjO4D
        gYwkCubpt8pOE+X48HdyKDxrJF0n47I7ctRQb3d0222W15UDvHG47bjyW0reKEhDjijkJAOeBjGO
        cV0MeOWONt8mPJOE5V45Is3aLnclPxlR2JchxC4r/wAS6FNR9xyHGlIUQcY/pWvcoNO68/v+5kac
        01V/+P2BF2nvsuR9OzI/eqShEdMjuVNNpaT1zgYJ8qbFUnNMVJqTUGgadNOyLfLvLLqIakyQ1FSQ
        di1dc4HIxjOemKZ6qTUXzwLlGk5LgbXO83LU2tLZpl+Cw7epDzEB2RFdCkyicJSo/u8cHcMcCjhj
        Sx7l14/AuWTdPlcnbNr1L2efZ50bB0tpaU/KurDIduEtjapJkqKFZWCCfAoeRz6cAGlQxPLLcG3s
        VMojtI7fFTFyXJGoDl1CkreOApaR+FxIGMEHHB8uhro44qCM8nZx/rXXFz1Y1JMeOsIdc5Uo8rxj
        n0FNSENkGRbLzNeR3kOQ5gZCUIJwKO10CSaJGS3sM9uSEj8SQnGPbNC5tdIHbfYbjzLMhxSmYrqF
        bSEhWCefdWePyoHklXISirDrV0kOwTFYbQpMdQJaWpIzkenOPmKR6q3XXYza6Nl6mubDbiUx2Evr
        UMqCgogD3/1qpS+eiCjou+qJrLk/YpttBXuSNiCB58nBPypKm1Fxx8WHst2ycWPSUOZIYXar3KTG
        lNbiVbWFhSepzyCPLB6e9DH/AEl7lz/kYouT4fA4TNnWyxPw3mWnVhTgRIWyC4pKvCRkcK+dMaTm
        mirko8i9ssclFvbZTFeuak8tp5BDZ8xkZxkY9qjknK06JFcdWSbViLW33jJjuMzI4Cltb9zSjt8h
        6dOvrSMO7+A8m1cLsrS/BFxjJbhwGFpaTuUdu3p1OOmOtb8fD9xnm01wiv4Nuk3+9GJaI6Soo25S
        eo8yPLpQarPDFG2DBOTpFiM6AvDNudEWxqnTWU92MkbG0kZJGfxn1x061ixNTlum6XwanjcFSVsa
        /wBiNVPBNuiacLzsRAecQ1tO9B653ZJIz0HStiliXusQ4y+BV7QslpxDTNrlNrdKSthTgWUeqsJ5
        AHPTyoH6cuWRqS4Q7c0NapLirW1LUhQB+8GT3i+v4MdPfP0odsV76DrwCr/pCJp0bkzXFPBsKWls
        pX4/Q+hpkcUMq5FSk4MSi3nWmm7b+17BrIpblNll9pqQoPMJPVC0H1/w/nQ/o8UpVXQ2OpywVqQq
        vtUvqrGxpoWy3SIkUpWkNMqaePmcnd4s496p6HbJzT5Yf6xuO1roc6Y7VzZESFM6fi7lqBEhJW09
        HwTlIIPQ5x5np0rLmwzbqX+BmPUqK4JrpvtRtU15pV10lcnpBeOFMrQ/tByTwoAnPPnzWPLCcb2t
        UaseeMq3IMNXPS94ucluVAu8a0yAoF15AIQvG1O/xfgB5wBmpGeRRT8h1CVquCstT6ph6euKDp+5
        JkXKE8HI77TZSglPCeVAbf0rr4YKS3T6Oflk4yqPYXvdo7RdYWmHMlamt86fOZ7z4WNL3OJSMnxD
        kZ+vFIhqscJOLVJDp4JyindtkGuGgf2bHee1Lc3m1tJ3FtxByk8cYVjOc9QPlWqOZzfsRneJR+5k
        deGnEIUmM4t3actoSCkf7RPl8qcn8iXS6J12dNade0vcZF5Wpuep/LYQjKQnbhAJ6gDnyxWXLKbz
        VDoZCtnPZveWokSKlLaGHUrGdwVuSfy6Gn47b5FzqiCvlpRe7yH90kkJ2evoTWt1YhWMIMpTrK2w
        jI5SCSSSPTNY8sVGdxGJ8E00v2b3292WReIe1uHFcDS1OE7EkgZJPl1HWsmXU44yUZPljoYnKNj1
        tzVNsX8Aw/bnmoDnd94WQATg8dOfnTI7JK/km6S4+BFvU2sLM0+/GioLbwJKgCpIz1wAfPHpTGlJ
        pMpScFaQu72jMXS1i0PNOxFKKQ9sBUCRySEnG3PtVKGyW5lue5UghA1fHiREw7ZcI7jed5Eh094g
        +Y58vlQuSbt2gl1wWXrZtv4dTuxO9wBS1Y5Udx5J86VhfI3KlRV+olrY0q+6wtTaypaSpBwSMdMi
        uhD7zFPoW7I4UN6LHL0RlzLOTubBzyPWuPmk/wBQ1Zp06TOkYbTaezmY6ltIWmSvCgOR4D50K/3E
        bX9rKru8uWxpYPsSnW3TeyCtCyFYwPMVrxpPJT+DJJ1H+ScatWozLG+VHvFxQVLz4icdSaRH7WiT
        +5FYR/8A85X8eTUbKB/CSRnHpmtj/wBqIiHM5EV/9RSP3SCceWadPoBEeurTQgFQbSD94c48wqnw
        +5AT4XANlLWxZrTJYWpt7xfeIOFdfUc0fe4nwb6f+9cvSnPGe4Ucq55yOa52r++I3F5Nw87HvjXc
        Orbw0jGxRHr6UiaTxcj7anwTLtHly06JtTiZToUogFQWckA0jRJObRs1TfpRGmkoMF/ep+Gw4S0s
        krbBJO33pspO+/gQkuSIQ/BNOzw8L6cVuyJUZoNpi17felNF2U8t5aWQApxRUQABgZNJgqdIZJt8
        sCadbbdceS6hK0jkBQyM0eobilQiPNkgS+9FuKERnltJK2shCikHI56VIK4WF5NNXAJuy2UgBsJz
        tHTOfSmRb9NMGX3MZ3pamLEpDCi2lSEKIQcAnHXjzpuLnl/kCQEh+Fg7ePlSp9leC4OyaRIQm4MI
        fcS27HSXEBRCV+IDkedc3PFOabRswN00PLh93OkNt+FCigFKeARx5VpgrXIEuxlJAF1uDYACEukJ
        T5DjyFHD7ED5ZHLshJjpUUgkjrjmtEOwJdEfDDK3XSplBOR1SD60x9gLo//Z
        IMG_EOF

        img_path=/tmp/imgfile.jpg
        base64 -d <<< cat $base64img >> "$img_path"
        curl -sS \
          -H 'Content-Type: multipart/form-data' \
          -F "chat_id=$TELEGRAM_CHAT_ID" \
          -F "photo=@$img_path" \
          "$ENDPOINT"
